import { Team, LeagueId } from '../types';
import { createTeamLogo, TEAM_LOGOS } from './teamLogos';
import { createGenericSquad } from './squadHelpers';

/**
 * Championship teams (24 teams)
 * These teams compete in the second tier of English football
 */
export const CHAMPIONSHIP_TEAMS: Team[] = [
    {
        id: 101,
        name: 'Leeds United',
        logo: createTeamLogo('', 'Leeds United'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 40,
        transferBudget: 10,
        tier: 'Mid',
        teamMorale: 'Normal',
        primaryColor: '#FFFFFF',
        secondaryColor: '#FFCD00',
        tactics: 'Attacking',
        squad: createGenericSquad(10100, 'Leeds')
    },
    {
        id: 102,
        name: 'Burnley',
        logo: createTeamLogo('', 'Burnley'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 35,
        transferBudget: 8,
        tier: 'Mid',
        teamMorale: 'Normal',
        primaryColor: '#6C1D45',
        secondaryColor: '#99D6EA',
        tactics: 'Defensive',
        squad: createGenericSquad(10200, 'Burnley')
    },
    {
        id: 103,
        name: 'Luton Town',
        logo: createTeamLogo('', 'Luton Town'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 30,
        transferBudget: 5,
        tier: 'Mid',
        teamMorale: 'Contento',
        primaryColor: '#F78F1E',
        secondaryColor: '#002D56',
        tactics: 'Balanced',
        squad: createGenericSquad(10300, 'Luton')
    },
    {
        id: 104,
        name: 'Sheffield Utd',
        logo: createTeamLogo('', 'Sheffield Utd'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 35,
        transferBudget: 8,
        tier: 'Mid',
        teamMorale: 'Normal',
        primaryColor: '#EE2737',
        secondaryColor: '#000000',
        tactics: 'Defensive',
        squad: createGenericSquad(10400, 'Sheffield Utd')
    },
    {
        id: 105,
        name: 'West Brom',
        logo: createTeamLogo('', 'West Brom'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 25,
        transferBudget: 5,
        tier: 'Mid',
        teamMorale: 'Normal',
        primaryColor: '#122F67',
        secondaryColor: '#FFFFFF',
        tactics: 'Balanced',
        squad: createGenericSquad(10500, 'West Brom')
    },
    {
        id: 106,
        name: 'Norwich City',
        logo: createTeamLogo('', 'Norwich City'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 25,
        transferBudget: 5,
        tier: 'Mid',
        teamMorale: 'Normal',
        primaryColor: '#FFF200',
        secondaryColor: '#00A650',
        tactics: 'Attacking',
        squad: createGenericSquad(10600, 'Norwich')
    },
    {
        id: 107,
        name: 'Hull City',
        logo: createTeamLogo('', 'Hull City'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 20,
        transferBudget: 4,
        tier: 'Lower',
        teamMorale: 'Normal',
        primaryColor: '#F5A12D',
        secondaryColor: '#000000',
        tactics: 'Attacking',
        squad: createGenericSquad(10700, 'Hull')
    },
    {
        id: 108,
        name: 'Coventry City',
        logo: createTeamLogo('', 'Coventry City'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 15,
        transferBudget: 3,
        tier: 'Lower',
        teamMorale: 'Contento',
        primaryColor: '#CC0000',
        secondaryColor: '#FFFFFF',
        tactics: 'Balanced',
        squad: createGenericSquad(10800, 'Coventry')
    },
    {
        id: 109,
        name: 'Middlesbrough',
        logo: createTeamLogo('', 'Middlesbrough'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 20,
        transferBudget: 4,
        tier: 'Mid',
        teamMorale: 'Normal',
        primaryColor: '#E03A3E',
        secondaryColor: '#FFFFFF',
        tactics: 'Balanced',
        squad: createGenericSquad(10900, 'Middlesbrough')
    },
    {
        id: 110,
        name: 'Preston',
        logo: createTeamLogo('', 'Preston'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 10,
        transferBudget: 2,
        tier: 'Lower',
        teamMorale: 'Normal',
        primaryColor: '#FFFFFF',
        secondaryColor: '#003399',
        tactics: 'Defensive',
        squad: createGenericSquad(11000, 'Preston')
    },
    {
        id: 111,
        name: 'Cardiff City',
        logo: createTeamLogo('', 'Cardiff City'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 15,
        transferBudget: 3,
        tier: 'Lower',
        teamMorale: 'Normal',
        primaryColor: '#0070B5',
        secondaryColor: '#FFFFFF',
        tactics: 'Defensive',
        squad: createGenericSquad(11100, 'Cardiff')
    },
    {
        id: 112,
        name: 'Bristol City',
        logo: createTeamLogo('', 'Bristol City'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 15,
        transferBudget: 3,
        tier: 'Lower',
        teamMorale: 'Normal',
        primaryColor: '#E30613',
        secondaryColor: '#FFFFFF',
        tactics: 'Balanced',
        squad: createGenericSquad(11200, 'Bristol City')
    },
    {
        id: 113,
        name: 'Sunderland',
        logo: createTeamLogo('', 'Sunderland'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 20,
        transferBudget: 5,
        tier: 'Mid',
        teamMorale: 'Contento',
        primaryColor: '#FF0000',
        secondaryColor: '#FFFFFF',
        tactics: 'Attacking',
        squad: createGenericSquad(11300, 'Sunderland')
    },
    {
        id: 114,
        name: 'Swansea City',
        logo: createTeamLogo('', 'Swansea City'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 15,
        transferBudget: 3,
        tier: 'Lower',
        teamMorale: 'Normal',
        primaryColor: '#FFFFFF',
        secondaryColor: '#000000',
        tactics: 'Attacking',
        squad: createGenericSquad(11400, 'Swansea')
    },
    {
        id: 115,
        name: 'Watford',
        logo: createTeamLogo('', 'Watford'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 25,
        transferBudget: 5,
        tier: 'Mid',
        teamMorale: 'Descontento',
        primaryColor: '#FBEE23',
        secondaryColor: '#ED2127',
        tactics: 'Attacking',
        squad: createGenericSquad(11500, 'Watford')
    },
    {
        id: 116,
        name: 'Millwall',
        logo: createTeamLogo('', 'Millwall'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 10,
        transferBudget: 2,
        tier: 'Lower',
        teamMorale: 'Normal',
        primaryColor: '#001F5B',
        secondaryColor: '#FFFFFF',
        tactics: 'Defensive',
        squad: createGenericSquad(11600, 'Millwall')
    },
    {
        id: 117,
        name: 'QPR',
        logo: createTeamLogo('', 'QPR'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 12,
        transferBudget: 2,
        tier: 'Lower',
        teamMorale: 'Normal',
        primaryColor: '#0054A6',
        secondaryColor: '#FFFFFF',
        tactics: 'Balanced',
        squad: createGenericSquad(11700, 'QPR')
    },
    {
        id: 118,
        name: 'Stoke City',
        logo: createTeamLogo('', 'Stoke City'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 20,
        transferBudget: 4,
        tier: 'Mid',
        teamMorale: 'Normal',
        primaryColor: '#E03A3E',
        secondaryColor: '#FFFFFF',
        tactics: 'Balanced',
        squad: createGenericSquad(11800, 'Stoke')
    },
    {
        id: 119,
        name: 'Blackburn',
        logo: createTeamLogo('', 'Blackburn'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 15,
        transferBudget: 3,
        tier: 'Lower',
        teamMorale: 'Normal',
        primaryColor: '#009EE0',
        secondaryColor: '#FFFFFF',
        tactics: 'Attacking',
        squad: createGenericSquad(11900, 'Blackburn')
    },
    {
        id: 120,
        name: 'Sheffield Wed',
        logo: createTeamLogo('', 'Sheffield Wed'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 12,
        transferBudget: 2,
        tier: 'Lower',
        teamMorale: 'Normal',
        primaryColor: '#0E00F7',
        secondaryColor: '#FFFFFF',
        tactics: 'Defensive',
        squad: createGenericSquad(12000, 'Sheffield Wed')
    },
    {
        id: 121,
        name: 'Plymouth',
        logo: createTeamLogo('', 'Plymouth'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 8,
        transferBudget: 1,
        tier: 'Lower',
        teamMorale: 'Contento',
        primaryColor: '#1B4835',
        secondaryColor: '#FFFFFF',
        tactics: 'Defensive',
        squad: createGenericSquad(12100, 'Plymouth')
    },
    {
        id: 122,
        name: 'Portsmouth',
        logo: createTeamLogo('', 'Portsmouth'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 10,
        transferBudget: 2,
        tier: 'Lower',
        teamMorale: 'Feliz',
        primaryColor: '#001489',
        secondaryColor: '#FFFFFF',
        tactics: 'Balanced',
        squad: createGenericSquad(12200, 'Portsmouth')
    },
    {
        id: 123,
        name: 'Derby County',
        logo: createTeamLogo('', 'Derby County'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 12,
        transferBudget: 2,
        tier: 'Lower',
        teamMorale: 'Feliz',
        primaryColor: '#FFFFFF',
        secondaryColor: '#000000',
        tactics: 'Balanced',
        squad: createGenericSquad(12300, 'Derby')
    },
    {
        id: 124,
        name: 'Oxford United',
        logo: createTeamLogo('', 'Oxford United'),
        leagueId: LeagueId.CHAMPIONSHIP,
        budget: 8,
        transferBudget: 1,
        tier: 'Lower',
        teamMorale: 'Feliz',
        primaryColor: '#F3A530',
        secondaryColor: '#002F5F',
        tactics: 'Defensive',
        squad: createGenericSquad(12400, 'Oxford')
    },
];
