
import React from 'react';
import { Team, LeagueId, Player } from './types';

// Premier League Team Logos
const createTeamLogo = (logoPath: string, teamName: string) => {
  return (
    <div className="w-12 h-12 relative flex items-center justify-center">
      <img
        src={logoPath}
        alt={`${teamName} logo`}
        className="w-full h-full object-contain drop-shadow-lg hover:scale-110 transition-transform duration-300"
      />
    </div>
  );
};

// Logo paths for all Premier League teams
// Logo paths for all Premier League teams
const TEAM_LOGOS = {
  'Arsenal': '/logos/Arsenal FC.png',
  'Aston Villa': '/logos/Aston Villa FC.png',
  'AFC Bournemouth': '/logos/AFC Bournemouth.png',
  'Brentford': '/logos/Brentford FC 512x.png',
  'Brighton': '/logos/Brighton Hove Albion.png',
  'Chelsea': '/logos/Chelsea FC.png',
  'Crystal Palace': '/logos/Crystal Palace FC.png',
  'Everton': '/logos/Everton FC.png',
  'Fulham': '/logos/Fulham FC.png',
  'Ipswich Town': '/logos/Ipswich Town FC.png',
  'Leicester City': '/logos/Leicester City FC.png',
  'Liverpool': '/logos/Liverpool FC.png',
  'Manchester City': '/logos/Manchester City FC.png',
  'Manchester United': '/logos/Manchester United FC.png',
  'Newcastle United': '/logos/Newcastle United FC.png',
  'Nottingham Forest': '/logos/Nottingham Forest FC.png',
  'Southampton': '/logos/Southampton FC.png',
  'Tottenham': '/logos/Tottenham Hotspur FC.png',
  'West Ham': '/logos/West Ham United FC.png',
  'Wolverhampton': '/logos/Wolverhampton Wanderers FC.png',
  // Championship
  'Leeds United': '/logos/Leeds United FC.png',
  'Burnley': '/logos/Burnley FC.png',
  'Luton Town': '/logos/Luton Town FC.png',
  'Sheffield Utd': '/logos/Sheffield United FC.png',
  'West Brom': '/logos/West Bromwich Albion FC.png',
  'Norwich City': '/logos/Norwich City FC.png',
  'Hull City': '/logos/Hull City FC.png',
  'Coventry City': '/logos/Coventry City FC.png',
  'Middlesbrough': '/logos/Middlesbrough FC.png',
  'Preston': '/logos/Preston North End FC.png',
  'Cardiff City': '/logos/Cardiff City FC.png',
  'Bristol City': '/logos/Bristol City FC.png',
  'Sunderland': '/logos/Sunderland AFC.png',
  'Swansea City': '/logos/Swansea City AFC.png',
  'Watford': '/logos/Watford FC.png',
  'Millwall': '/logos/Millwall FC.png',
  'QPR': '/logos/Queens Park Rangers FC.png',
  'Stoke City': '/logos/Stoke City FC.png',
  'Blackburn': '/logos/Blackburn Rovers FC.png',
  'Sheffield Wed': '/logos/Sheffield Wednesday FC.PNG',
  'Plymouth': '/logos/Plymouth Argyle FC.png',
  'Portsmouth': '/logos/Portsmouth FC.png',
  'Derby County': '/logos/Derby County FC.png',
  'Oxford United': '/logos/Oxford United FC.png',
};

// Helper to generate generic squad for Championship teams
const createGenericSquad = (startId: number, teamName: string): Player[] => {
  const positions: { pos: 'POR' | 'DEF' | 'CEN' | 'DEL', count: number }[] = [
    { pos: 'POR', count: 2 },
    { pos: 'DEF', count: 6 },
    { pos: 'CEN', count: 6 },
    { pos: 'DEL', count: 4 }
  ];

  let squad: Player[] = [];
  let idCounter = startId;

  positions.forEach(({ pos, count }) => {
    for (let i = 0; i < count; i++) {
      squad.push({
        id: idCounter++,
        name: `${teamName} ${pos} ${i + 1}`, // Placeholder name
        position: pos,
        rating: Math.floor(65 + Math.random() * 10), // Rating 65-75 for Championship
        value: Math.floor(1 + Math.random() * 10),
        wage: Math.floor(5000 + Math.random() * 15000),
        morale: 'Normal',
        contractYears: Math.floor(1 + Math.random() * 3),
        age: Math.floor(18 + Math.random() * 15)
      });
    }
  });

  return squad;
};

export const TEAMS: Team[] = [
  // ... (Existing Premier League Teams - kept as is)
  {
    id: 5, name: 'Manchester City', logo: createTeamLogo(TEAM_LOGOS['Manchester City'], 'Manchester City'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 700, transferBudget: 180, tier: 'Top', teamMorale: 'Feliz',
    primaryColor: '#6CABDD', secondaryColor: '#1C2C5B', tactics: 'Attacking',
    squad: [
      { id: 501, name: 'E. Haaland', position: 'DEL', rating: 91, value: 180, wage: 375000, morale: 'Contento', contractYears: 4 },
      { id: 502, name: 'K. De Bruyne', position: 'CEN', rating: 91, value: 80, wage: 400000, morale: 'Feliz', contractYears: 2 },
      { id: 503, name: 'Rodri', position: 'CEN', rating: 89, value: 110, wage: 220000, morale: 'Contento', contractYears: 5 },
      { id: 504, name: 'P. Foden', position: 'CEN', rating: 88, value: 130, wage: 225000, morale: 'Feliz', contractYears: 5 },
      { id: 505, name: 'R. Dias', position: 'DEF', rating: 88, value: 85, wage: 180000, morale: 'Contento', contractYears: 4 },
      { id: 506, name: 'Ederson', position: 'POR', rating: 88, value: 55, wage: 120000, morale: 'Feliz', contractYears: 3 },
      { id: 507, name: 'J. Gvardiol', position: 'DEF', rating: 86, value: 80, wage: 150000, morale: 'Contento', contractYears: 5 },
      { id: 508, name: 'J. Stones', position: 'DEF', rating: 85, value: 60, wage: 250000, morale: 'Normal', contractYears: 3 },
      { id: 509, name: 'K. Walker', position: 'DEF', rating: 84, value: 30, wage: 175000, morale: 'Contento', contractYears: 2 },
      { id: 510, name: 'J. Grealish', position: 'DEL', rating: 84, value: 70, wage: 300000, morale: 'Normal', contractYears: 4 },
      { id: 511, name: 'J. Álvarez', position: 'DEL', rating: 85, value: 90, wage: 100000, morale: 'Contento', contractYears: 4 },
      { id: 512, name: 'B. Silva', position: 'CEN', rating: 88, value: 80, wage: 150000, morale: 'Feliz', contractYears: 3 },
      { id: 513, name: 'M. Akanji', position: 'DEF', rating: 83, value: 45, wage: 180000, morale: 'Contento', contractYears: 4 },
      { id: 514, name: 'N. Aké', position: 'DEF', rating: 82, value: 40, wage: 90000, morale: 'Contento', contractYears: 3 },
      { id: 515, name: 'M. Nunes', position: 'CEN', rating: 80, value: 45, wage: 130000, morale: 'Normal', contractYears: 5 },
      { id: 516, name: 'S. Ortega', position: 'POR', rating: 80, value: 10, wage: 55000, morale: 'Contento', contractYears: 2 },
    ],
  },
  // ... (Other Premier League teams would be here, assuming I am appending to the end or replacing the array. 
  // Since I cannot see the full file content in the tool input, I will assume I need to append the new teams to the existing list.
  // However, replace_file_content requires exact match. 
  // Strategy: I will use the END of the file to append the new teams.)

  // --- CHAMPIONSHIP TEAMS ---
  { id: 101, name: 'Leeds United', logo: createTeamLogo(TEAM_LOGOS['Leeds United'], 'Leeds United'), leagueId: LeagueId.CHAMPIONSHIP, budget: 40, transferBudget: 10, tier: 'Mid', teamMorale: 'Normal', primaryColor: '#FFFFFF', secondaryColor: '#FFCD00', tactics: 'Attacking', squad: createGenericSquad(10100, 'Leeds') },
  { id: 102, name: 'Burnley', logo: createTeamLogo(TEAM_LOGOS['Burnley'], 'Burnley'), leagueId: LeagueId.CHAMPIONSHIP, budget: 35, transferBudget: 8, tier: 'Mid', teamMorale: 'Normal', primaryColor: '#6C1D45', secondaryColor: '#99D6EA', tactics: 'Defensive', squad: createGenericSquad(10200, 'Burnley') },
  { id: 103, name: 'Luton Town', logo: createTeamLogo(TEAM_LOGOS['Luton Town'], 'Luton Town'), leagueId: LeagueId.CHAMPIONSHIP, budget: 30, transferBudget: 5, tier: 'Mid', teamMorale: 'Contento', primaryColor: '#F78F1E', secondaryColor: '#002D56', tactics: 'Balanced', squad: createGenericSquad(10300, 'Luton') },
  { id: 104, name: 'Sheffield Utd', logo: createTeamLogo(TEAM_LOGOS['Sheffield Utd'], 'Sheffield Utd'), leagueId: LeagueId.CHAMPIONSHIP, budget: 35, transferBudget: 8, tier: 'Mid', teamMorale: 'Normal', primaryColor: '#EE2737', secondaryColor: '#000000', tactics: 'Defensive', squad: createGenericSquad(10400, 'Sheffield Utd') },
  { id: 105, name: 'West Brom', logo: createTeamLogo(TEAM_LOGOS['West Brom'], 'West Brom'), leagueId: LeagueId.CHAMPIONSHIP, budget: 25, transferBudget: 5, tier: 'Mid', teamMorale: 'Normal', primaryColor: '#122F67', secondaryColor: '#FFFFFF', tactics: 'Balanced', squad: createGenericSquad(10500, 'West Brom') },
  { id: 106, name: 'Norwich City', logo: createTeamLogo(TEAM_LOGOS['Norwich City'], 'Norwich City'), leagueId: LeagueId.CHAMPIONSHIP, budget: 25, transferBudget: 5, tier: 'Mid', teamMorale: 'Normal', primaryColor: '#FFF200', secondaryColor: '#00A650', tactics: 'Attacking', squad: createGenericSquad(10600, 'Norwich') },
  { id: 107, name: 'Hull City', logo: createTeamLogo(TEAM_LOGOS['Hull City'], 'Hull City'), leagueId: LeagueId.CHAMPIONSHIP, budget: 20, transferBudget: 4, tier: 'Lower', teamMorale: 'Normal', primaryColor: '#F5A12D', secondaryColor: '#000000', tactics: 'Attacking', squad: createGenericSquad(10700, 'Hull') },
  { id: 108, name: 'Coventry City', logo: createTeamLogo(TEAM_LOGOS['Coventry City'], 'Coventry City'), leagueId: LeagueId.CHAMPIONSHIP, budget: 15, transferBudget: 3, tier: 'Lower', teamMorale: 'Contento', primaryColor: '#CC0000', secondaryColor: '#FFFFFF', tactics: 'Balanced', squad: createGenericSquad(10800, 'Coventry') },
  { id: 109, name: 'Middlesbrough', logo: createTeamLogo(TEAM_LOGOS['Middlesbrough'], 'Middlesbrough'), leagueId: LeagueId.CHAMPIONSHIP, budget: 20, transferBudget: 4, tier: 'Mid', teamMorale: 'Normal', primaryColor: '#E03A3E', secondaryColor: '#FFFFFF', tactics: 'Balanced', squad: createGenericSquad(10900, 'Middlesbrough') },
  { id: 110, name: 'Preston', logo: createTeamLogo(TEAM_LOGOS['Preston'], 'Preston'), leagueId: LeagueId.CHAMPIONSHIP, budget: 10, transferBudget: 2, tier: 'Lower', teamMorale: 'Normal', primaryColor: '#FFFFFF', secondaryColor: '#003399', tactics: 'Defensive', squad: createGenericSquad(11000, 'Preston') },
  { id: 111, name: 'Cardiff City', logo: createTeamLogo(TEAM_LOGOS['Cardiff City'], 'Cardiff City'), leagueId: LeagueId.CHAMPIONSHIP, budget: 15, transferBudget: 3, tier: 'Lower', teamMorale: 'Normal', primaryColor: '#0070B5', secondaryColor: '#FFFFFF', tactics: 'Defensive', squad: createGenericSquad(11100, 'Cardiff') },
  { id: 112, name: 'Bristol City', logo: createTeamLogo(TEAM_LOGOS['Bristol City'], 'Bristol City'), leagueId: LeagueId.CHAMPIONSHIP, budget: 15, transferBudget: 3, tier: 'Lower', teamMorale: 'Normal', primaryColor: '#E30613', secondaryColor: '#FFFFFF', tactics: 'Balanced', squad: createGenericSquad(11200, 'Bristol City') },
  { id: 113, name: 'Sunderland', logo: createTeamLogo(TEAM_LOGOS['Sunderland'], 'Sunderland'), leagueId: LeagueId.CHAMPIONSHIP, budget: 20, transferBudget: 5, tier: 'Mid', teamMorale: 'Contento', primaryColor: '#FF0000', secondaryColor: '#FFFFFF', tactics: 'Attacking', squad: createGenericSquad(11300, 'Sunderland') },
  { id: 114, name: 'Swansea City', logo: createTeamLogo(TEAM_LOGOS['Swansea City'], 'Swansea City'), leagueId: LeagueId.CHAMPIONSHIP, budget: 15, transferBudget: 3, tier: 'Lower', teamMorale: 'Normal', primaryColor: '#FFFFFF', secondaryColor: '#000000', tactics: 'Attacking', squad: createGenericSquad(11400, 'Swansea') },
  { id: 115, name: 'Watford', logo: createTeamLogo(TEAM_LOGOS['Watford'], 'Watford'), leagueId: LeagueId.CHAMPIONSHIP, budget: 25, transferBudget: 5, tier: 'Mid', teamMorale: 'Descontento', primaryColor: '#FBEE23', secondaryColor: '#ED2127', tactics: 'Attacking', squad: createGenericSquad(11500, 'Watford') },
  { id: 116, name: 'Millwall', logo: createTeamLogo(TEAM_LOGOS['Millwall'], 'Millwall'), leagueId: LeagueId.CHAMPIONSHIP, budget: 10, transferBudget: 2, tier: 'Lower', teamMorale: 'Normal', primaryColor: '#001F5B', secondaryColor: '#FFFFFF', tactics: 'Defensive', squad: createGenericSquad(11600, 'Millwall') },
  { id: 117, name: 'QPR', logo: createTeamLogo(TEAM_LOGOS['QPR'], 'QPR'), leagueId: LeagueId.CHAMPIONSHIP, budget: 12, transferBudget: 2, tier: 'Lower', teamMorale: 'Normal', primaryColor: '#0054A6', secondaryColor: '#FFFFFF', tactics: 'Balanced', squad: createGenericSquad(11700, 'QPR') },
  { id: 118, name: 'Stoke City', logo: createTeamLogo(TEAM_LOGOS['Stoke City'], 'Stoke City'), leagueId: LeagueId.CHAMPIONSHIP, budget: 20, transferBudget: 4, tier: 'Mid', teamMorale: 'Normal', primaryColor: '#E03A3E', secondaryColor: '#FFFFFF', tactics: 'Balanced', squad: createGenericSquad(11800, 'Stoke') },
  { id: 119, name: 'Blackburn', logo: createTeamLogo(TEAM_LOGOS['Blackburn'], 'Blackburn'), leagueId: LeagueId.CHAMPIONSHIP, budget: 15, transferBudget: 3, tier: 'Lower', teamMorale: 'Normal', primaryColor: '#009EE0', secondaryColor: '#FFFFFF', tactics: 'Attacking', squad: createGenericSquad(11900, 'Blackburn') },
  { id: 120, name: 'Sheffield Wed', logo: createTeamLogo(TEAM_LOGOS['Sheffield Wed'], 'Sheffield Wed'), leagueId: LeagueId.CHAMPIONSHIP, budget: 12, transferBudget: 2, tier: 'Lower', teamMorale: 'Normal', primaryColor: '#0E00F7', secondaryColor: '#FFFFFF', tactics: 'Defensive', squad: createGenericSquad(12000, 'Sheffield Wed') },
  { id: 121, name: 'Plymouth', logo: createTeamLogo(TEAM_LOGOS['Plymouth'], 'Plymouth'), leagueId: LeagueId.CHAMPIONSHIP, budget: 8, transferBudget: 1, tier: 'Lower', teamMorale: 'Contento', primaryColor: '#1B4835', secondaryColor: '#FFFFFF', tactics: 'Defensive', squad: createGenericSquad(12100, 'Plymouth') },
  { id: 122, name: 'Portsmouth', logo: createTeamLogo(TEAM_LOGOS['Portsmouth'], 'Portsmouth'), leagueId: LeagueId.CHAMPIONSHIP, budget: 10, transferBudget: 2, tier: 'Lower', teamMorale: 'Feliz', primaryColor: '#001489', secondaryColor: '#FFFFFF', tactics: 'Balanced', squad: createGenericSquad(12200, 'Portsmouth') },
  { id: 123, name: 'Derby County', logo: createTeamLogo(TEAM_LOGOS['Derby County'], 'Derby County'), leagueId: LeagueId.CHAMPIONSHIP, budget: 12, transferBudget: 2, tier: 'Lower', teamMorale: 'Feliz', primaryColor: '#FFFFFF', secondaryColor: '#000000', tactics: 'Balanced', squad: createGenericSquad(12300, 'Derby') },
  { id: 124, name: 'Oxford United', logo: createTeamLogo(TEAM_LOGOS['Oxford United'], 'Oxford United'), leagueId: LeagueId.CHAMPIONSHIP, budget: 8, transferBudget: 1, tier: 'Lower', teamMorale: 'Feliz', primaryColor: '#F3A530', secondaryColor: '#002F5F', tactics: 'Defensive', squad: createGenericSquad(12400, 'Oxford') },
  {
    id: 1, name: 'Arsenal', logo: createTeamLogo(TEAM_LOGOS['Arsenal'], 'Arsenal'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 250, transferBudget: 80, tier: 'Top', teamMorale: 'Feliz',
    primaryColor: '#EF0107', secondaryColor: '#063672', tactics: 'Attacking',
    squad: [
      { id: 101, name: 'B. Saka', position: 'DEL', rating: 88, value: 120, wage: 195000, morale: 'Feliz', contractYears: 5 },
      { id: 102, name: 'M. Ødegaard', position: 'CEN', rating: 87, value: 90, wage: 115000, morale: 'Feliz', contractYears: 4 },
      { id: 103, name: 'W. Saliba', position: 'DEF', rating: 86, value: 80, wage: 190000, morale: 'Contento', contractYears: 5 },
      { id: 104, name: 'D. Raya', position: 'POR', rating: 84, value: 35, wage: 85000, morale: 'Contento', contractYears: 3 },
      { id: 105, name: 'D. Rice', position: 'CEN', rating: 87, value: 110, wage: 240000, morale: 'Feliz', contractYears: 5 },
      { id: 106, name: 'Gabriel M.', position: 'DEL', rating: 85, value: 85, wage: 180000, morale: 'Contento', contractYears: 4 },
      { id: 107, name: 'Gabriel J.', position: 'DEL', rating: 84, value: 75, wage: 265000, morale: 'Normal', contractYears: 4 },
      { id: 108, name: 'Gabriel', position: 'DEF', rating: 84, value: 65, wage: 100000, morale: 'Contento', contractYears: 4 },
      { id: 109, name: 'B. White', position: 'DEF', rating: 83, value: 55, wage: 150000, morale: 'Contento', contractYears: 5 },
      { id: 110, name: 'K. Havertz', position: 'CEN', rating: 83, value: 60, wage: 280000, morale: 'Contento', contractYears: 5 },
      { id: 111, name: 'O. Zinchenko', position: 'DEF', rating: 81, value: 40, wage: 150000, morale: 'Normal', contractYears: 3 },
      { id: 112, name: 'Jorginho', position: 'CEN', rating: 82, value: 20, wage: 110000, morale: 'Contento', contractYears: 1 },
      { id: 113, name: 'T. Partey', position: 'CEN', rating: 84, value: 35, wage: 200000, morale: 'Normal', contractYears: 2 },
      { id: 114, name: 'L. Trossard', position: 'DEL', rating: 82, value: 40, wage: 90000, morale: 'Contento', contractYears: 3 },
      { id: 115, name: 'A. Ramsdale', position: 'POR', rating: 82, value: 30, wage: 120000, morale: 'Descontento', contractYears: 4 },
      { id: 116, name: 'J. Timber', position: 'DEF', rating: 80, value: 40, wage: 90000, morale: 'Contento', contractYears: 5 },
    ],
  },
  {
    id: 4, name: 'Liverpool', logo: createTeamLogo(TEAM_LOGOS['Liverpool'], 'Liverpool'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 480, transferBudget: 120, tier: 'Top', teamMorale: 'Feliz',
    primaryColor: '#C8102E', secondaryColor: '#00B2A9', tactics: 'Attacking',
    squad: [
      { id: 401, name: 'M. Salah', position: 'DEL', rating: 90, value: 100, wage: 350000, morale: 'Contento', contractYears: 2 },
      { id: 402, name: 'Alisson', position: 'POR', rating: 89, value: 65, wage: 150000, morale: 'Feliz', contractYears: 4 },
      { id: 403, name: 'V. van Dijk', position: 'DEF', rating: 89, value: 50, wage: 220000, morale: 'Feliz', contractYears: 3 },
      { id: 404, name: 'T. Alexander-Arnold', position: 'DEF', rating: 87, value: 80, wage: 180000, morale: 'Feliz', contractYears: 3 },
      { id: 405, name: 'D. Jota', position: 'DEL', rating: 85, value: 65, wage: 140000, morale: 'Contento', contractYears: 4 },
      { id: 406, name: 'A. Robertson', position: 'DEF', rating: 86, value: 55, wage: 160000, morale: 'Contento', contractYears: 3 },
      { id: 407, name: 'L. Díaz', position: 'DEL', rating: 84, value: 75, wage: 120000, morale: 'Contento', contractYears: 4 },
      { id: 408, name: 'D. Núñez', position: 'DEL', rating: 83, value: 70, wage: 140000, morale: 'Normal', contractYears: 5 },
      { id: 409, name: 'A. Mac Allister', position: 'CEN', rating: 84, value: 75, wage: 150000, morale: 'Feliz', contractYears: 5 },
      { id: 410, name: 'D. Szoboszlai', position: 'CEN', rating: 83, value: 75, wage: 120000, morale: 'Contento', contractYears: 5 },
      { id: 411, name: 'I. Konaté', position: 'DEF', rating: 83, value: 45, wage: 70000, morale: 'Contento', contractYears: 4 },
      { id: 412, name: 'C. Gakpo', position: 'DEL', rating: 83, value: 60, wage: 120000, morale: 'Normal', contractYears: 5 },
      { id: 413, name: 'Thiago', position: 'CEN', rating: 84, value: 15, wage: 200000, morale: 'Normal', contractYears: 1 },
      { id: 414, name: 'J. Gomez', position: 'DEF', rating: 81, value: 30, wage: 85000, morale: 'Contento', contractYears: 3 },
      { id: 415, name: 'W. Endo', position: 'CEN', rating: 80, value: 20, wage: 50000, morale: 'Contento', contractYears: 3 },
      { id: 416, name: 'C. Kelleher', position: 'POR', rating: 78, value: 15, wage: 30000, morale: 'Contento', contractYears: 3 },
    ],
  },
  {
    id: 6, name: 'Manchester Utd', logo: createTeamLogo(TEAM_LOGOS['Manchester United'], 'Manchester United'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 650, transferBudget: 140, tier: 'Top', teamMorale: 'Contento',
    primaryColor: '#DA291C', secondaryColor: '#FBE122', tactics: 'Attacking',
    squad: [
      { id: 601, name: 'B. Fernandes', position: 'CEN', rating: 88, value: 90, wage: 240000, morale: 'Contento', contractYears: 4 },
      { id: 602, name: 'M. Rashford', position: 'DEL', rating: 85, value: 80, wage: 300000, morale: 'Normal', contractYears: 3 },
      { id: 603, name: 'Casemiro', position: 'CEN', rating: 87, value: 40, wage: 350000, morale: 'Contento', contractYears: 2 },
      { id: 604, name: 'L. Martínez', position: 'DEF', rating: 86, value: 60, wage: 120000, morale: 'Feliz', contractYears: 4 },
      { id: 605, name: 'A. Onana', position: 'POR', rating: 85, value: 50, wage: 120000, morale: 'Contento', contractYears: 5 },
      { id: 606, name: 'R. Varane', position: 'DEF', rating: 85, value: 35, wage: 340000, morale: 'Normal', contractYears: 1 },
      { id: 607, name: 'M. Mount', position: 'CEN', rating: 82, value: 60, wage: 250000, morale: 'Normal', contractYears: 5 },
      { id: 608, name: 'Antony', position: 'DEL', rating: 81, value: 50, wage: 200000, morale: 'Descontento', contractYears: 4 },
      { id: 609, name: 'L. Shaw', position: 'DEF', rating: 83, value: 40, wage: 150000, morale: 'Contento', contractYears: 3 },
      { id: 610, name: 'K. Mainoo', position: 'CEN', rating: 78, value: 50, wage: 20000, morale: 'Feliz', contractYears: 4 },
      { id: 611, name: 'R. Højlund', position: 'DEL', rating: 79, value: 65, wage: 85000, morale: 'Contento', contractYears: 5 },
      { id: 612, name: 'A. Garnacho', position: 'DEL', rating: 78, value: 55, wage: 50000, morale: 'Feliz', contractYears: 5 },
      { id: 613, name: 'H. Maguire', position: 'DEF', rating: 80, value: 20, wage: 190000, morale: 'Normal', contractYears: 2 },
      { id: 614, name: 'D. Dalot', position: 'DEF', rating: 80, value: 35, wage: 85000, morale: 'Contento', contractYears: 4 },
      { id: 615, name: 'S. Amrabat', position: 'CEN', rating: 80, value: 25, wage: 65000, morale: 'Normal', contractYears: 1 },
      { id: 616, name: 'A. Bayindir', position: 'POR', rating: 77, value: 10, wage: 40000, morale: 'Normal', contractYears: 4 },
    ],
  },
  {
    id: 3, name: 'Chelsea', logo: createTeamLogo(TEAM_LOGOS['Chelsea'], 'Chelsea'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 450, transferBudget: 150, tier: 'Top', teamMorale: 'Contento',
    primaryColor: '#034694', secondaryColor: '#EE242C', tactics: 'Balanced',
    squad: [
      { id: 301, name: 'C. Palmer', position: 'CEN', rating: 84, value: 80, wage: 75000, morale: 'Feliz', contractYears: 5 },
      { id: 302, name: 'E. Fernández', position: 'CEN', rating: 83, value: 80, wage: 180000, morale: 'Contento', contractYears: 6 },
      { id: 303, name: 'R. James', position: 'DEF', rating: 85, value: 65, wage: 250000, morale: 'Normal', contractYears: 4 },
      { id: 304, name: 'C. Nkunku', position: 'DEL', rating: 86, value: 80, wage: 195000, morale: 'Contento', contractYears: 6 },
      { id: 305, name: 'M. Caicedo', position: 'CEN', rating: 82, value: 90, wage: 150000, morale: 'Normal', contractYears: 7 },
      { id: 306, name: 'R. Sterling', position: 'DEL', rating: 84, value: 55, wage: 325000, morale: 'Normal', contractYears: 3 },
      { id: 307, name: 'R. Sánchez', position: 'POR', rating: 81, value: 30, wage: 95000, morale: 'Normal', contractYears: 6 },
      { id: 308, name: 'B. Chilwell', position: 'DEF', rating: 83, value: 45, wage: 200000, morale: 'Normal', contractYears: 4 },
      { id: 309, name: 'M. Mudryk', position: 'DEL', rating: 78, value: 50, wage: 100000, morale: 'Normal', contractYears: 7 },
      { id: 310, name: 'N. Jackson', position: 'DEL', rating: 78, value: 45, wage: 65000, morale: 'Contento', contractYears: 7 },
      { id: 311, name: 'A. Disasi', position: 'DEF', rating: 80, value: 35, wage: 80000, morale: 'Contento', contractYears: 5 },
      { id: 312, name: 'L. Colwill', position: 'DEF', rating: 79, value: 55, wage: 100000, morale: 'Feliz', contractYears: 6 },
      { id: 313, name: 'C. Gallagher', position: 'CEN', rating: 81, value: 50, wage: 50000, morale: 'Contento', contractYears: 2 },
      { id: 314, name: 'M. Gusto', position: 'DEF', rating: 78, value: 40, wage: 65000, morale: 'Contento', contractYears: 5 },
      { id: 315, name: 'D. Petrovic', position: 'POR', rating: 77, value: 18, wage: 40000, morale: 'Contento', contractYears: 6 },
      { id: 316, name: 'T. Silva', position: 'DEF', rating: 84, value: 5, wage: 110000, morale: 'Feliz', contractYears: 1 },
    ],
  },
  {
    id: 8, name: 'Tottenham', logo: createTeamLogo(TEAM_LOGOS['Tottenham'], 'Tottenham'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 400, transferBudget: 90, tier: 'Mid', teamMorale: 'Contento',
    primaryColor: '#132257', secondaryColor: '#FFFFFF', tactics: 'Attacking',
    squad: [
      { id: 801, name: 'Son H.M.', position: 'DEL', rating: 87, value: 60, wage: 190000, morale: 'Feliz', contractYears: 2 },
      { id: 802, name: 'J. Maddison', position: 'CEN', rating: 84, value: 70, wage: 170000, morale: 'Contento', contractYears: 4 },
      { id: 803, name: 'C. Romero', position: 'DEF', rating: 83, value: 60, wage: 165000, morale: 'Contento', contractYears: 4 },
      { id: 804, name: 'G. Vicario', position: 'POR', rating: 84, value: 40, wage: 75000, morale: 'Feliz', contractYears: 5 },
      { id: 805, name: 'D. Kulusevski', position: 'DEL', rating: 82, value: 60, wage: 110000, morale: 'Contento', contractYears: 5 },
      { id: 806, name: 'Richarlison', position: 'DEL', rating: 81, value: 50, wage: 175000, morale: 'Normal', contractYears: 4 },
      { id: 807, name: 'M. van de Ven', position: 'DEF', rating: 80, value: 50, wage: 50000, morale: 'Feliz', contractYears: 6 },
      { id: 808, name: 'P. Porro', position: 'DEF', rating: 81, value: 45, wage: 65000, morale: 'Contento', contractYears: 5 },
      { id: 809, name: 'D. Udogie', position: 'DEF', rating: 79, value: 45, wage: 75000, morale: 'Contento', contractYears: 6 },
      { id: 810, name: 'Y. Bissouma', position: 'CEN', rating: 81, value: 40, wage: 55000, morale: 'Normal', contractYears: 3 },
      { id: 811, name: 'P. M. Sarr', position: 'CEN', rating: 78, value: 40, wage: 30000, morale: 'Contento', contractYears: 5 },
      { id: 812, name: 'B. Johnson', position: 'DEL', rating: 78, value: 40, wage: 70000, morale: 'Normal', contractYears: 5 },
      { id: 813, name: 'R. Bentancur', position: 'CEN', rating: 82, value: 40, wage: 75000, morale: 'Contento', contractYears: 3 },
      { id: 814, name: 'G. Lo Celso', position: 'CEN', rating: 80, value: 25, wage: 70000, morale: 'Descontento', contractYears: 2 },
      { id: 815, name: 'F. Forster', position: 'POR', rating: 74, value: 2, wage: 35000, morale: 'Normal', contractYears: 1 },
      { id: 816, name: 'B. Davies', position: 'DEF', rating: 78, value: 15, wage: 80000, morale: 'Contento', contractYears: 2 },
    ],
  },
  {
    id: 2, name: 'Aston Villa', logo: createTeamLogo(TEAM_LOGOS['Aston Villa'], 'Aston Villa'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 180, transferBudget: 50, tier: 'Mid', teamMorale: 'Feliz',
    primaryColor: '#670E36', secondaryColor: '#95BJE5', tactics: 'Balanced',
    squad: [
      { id: 201, name: 'O. Watkins', position: 'DEL', rating: 85, value: 65, wage: 130000, morale: 'Feliz', contractYears: 4 },
      { id: 202, name: 'Douglas Luiz', position: 'CEN', rating: 83, value: 60, wage: 75000, morale: 'Contento', contractYears: 3 },
      { id: 203, name: 'E. Martínez', position: 'POR', rating: 85, value: 30, wage: 100000, morale: 'Feliz', contractYears: 4 },
      { id: 204, name: 'M. Diaby', position: 'DEL', rating: 84, value: 65, wage: 130000, morale: 'Contento', contractYears: 5 },
      { id: 205, name: 'Pau Torres', position: 'DEF', rating: 83, value: 50, wage: 100000, morale: 'Feliz', contractYears: 5 },
      { id: 206, name: 'J. McGinn', position: 'CEN', rating: 82, value: 40, wage: 80000, morale: 'Feliz', contractYears: 4 },
      { id: 207, name: 'L. Bailey', position: 'DEL', rating: 80, value: 40, wage: 100000, morale: 'Contento', contractYears: 3 },
      { id: 208, name: 'E. Konsa', position: 'DEF', rating: 81, value: 35, wage: 75000, morale: 'Contento', contractYears: 4 },
      { id: 209, name: 'B. Kamara', position: 'CEN', rating: 82, value: 45, wage: 150000, morale: 'Contento', contractYears: 4 },
      { id: 210, name: 'Diego Carlos', position: 'DEF', rating: 81, value: 20, wage: 100000, morale: 'Normal', contractYears: 3 },
      { id: 211, name: 'M. Cash', position: 'DEF', rating: 79, value: 25, wage: 65000, morale: 'Contento', contractYears: 4 },
      { id: 212, name: 'Y. Tielemans', position: 'CEN', rating: 80, value: 25, wage: 150000, morale: 'Normal', contractYears: 4 },
      { id: 213, name: 'Álex Moreno', position: 'DEF', rating: 80, value: 20, wage: 50000, morale: 'Contento', contractYears: 3 },
      { id: 214, name: 'L. Digne', position: 'DEF', rating: 79, value: 18, wage: 120000, morale: 'Normal', contractYears: 2 },
      { id: 215, name: 'R. Olsen', position: 'POR', rating: 75, value: 5, wage: 35000, morale: 'Normal', contractYears: 2 },
      { id: 216, name: 'J. Ramsey', position: 'CEN', rating: 79, value: 40, wage: 70000, morale: 'Contento', contractYears: 5 },
    ],
  },
  {
    id: 7, name: 'Newcastle Utd', logo: createTeamLogo(TEAM_LOGOS['Newcastle United'], 'Newcastle United'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 300, transferBudget: 70, tier: 'Mid', teamMorale: 'Contento',
    primaryColor: '#241F20', secondaryColor: '#FFFFFF', tactics: 'Balanced',
    squad: [
      { id: 701, name: 'B. Guimarães', position: 'CEN', rating: 86, value: 85, wage: 160000, morale: 'Contento', contractYears: 5 },
      { id: 702, name: 'A. Isak', position: 'DEL', rating: 84, value: 75, wage: 120000, morale: 'Contento', contractYears: 4 },
      { id: 703, name: 'S. Tonali', position: 'CEN', rating: 85, value: 60, wage: 150000, morale: 'Normal', contractYears: 4 },
      { id: 704, name: 'S. Botman', position: 'DEF', rating: 84, value: 55, wage: 90000, morale: 'Contento', contractYears: 5 },
      { id: 705, name: 'K. Trippier', position: 'DEF', rating: 85, value: 20, wage: 120000, morale: 'Feliz', contractYears: 2 },
      { id: 706, name: 'N. Pope', position: 'POR', rating: 83, value: 25, wage: 60000, morale: 'Contento', contractYears: 3 },
      { id: 707, name: 'Joelinton', position: 'CEN', rating: 82, value: 45, wage: 85000, morale: 'Contento', contractYears: 3 },
      { id: 708, name: 'A. Gordon', position: 'DEL', rating: 80, value: 50, wage: 60000, morale: 'Contento', contractYears: 4 },
      { id: 709, name: 'H. Barnes', position: 'DEL', rating: 80, value: 35, wage: 80000, morale: 'Normal', contractYears: 5 },
      { id: 710, name: 'F. Schär', position: 'DEF', rating: 81, value: 20, wage: 40000, morale: 'Contento', contractYears: 2 },
      { id: 711, name: 'C. Wilson', position: 'DEL', rating: 81, value: 20, wage: 45000, morale: 'Contento', contractYears: 2 },
      { id: 712, name: 'D. Burn', position: 'DEF', rating: 79, value: 15, wage: 55000, morale: 'Contento', contractYears: 2 },
      { id: 713, name: 'S. Longstaff', position: 'CEN', rating: 78, value: 25, wage: 50000, morale: 'Contento', contractYears: 3 },
      { id: 714, name: 'J. Willock', position: 'CEN', rating: 79, value: 30, wage: 90000, morale: 'Normal', contractYears: 4 },
      { id: 715, name: 'M. Almiron', position: 'DEL', rating: 81, value: 30, wage: 60000, morale: 'Contento', contractYears: 3 },
      { id: 716, name: 'M. Dubravka', position: 'POR', rating: 79, value: 5, wage: 40000, morale: 'Normal', contractYears: 2 },
    ],
  },
  {
    id: 9, name: 'West Ham', logo: createTeamLogo(TEAM_LOGOS['West Ham'], 'West Ham'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 150, transferBudget: 40, tier: 'Mid', teamMorale: 'Normal',
    primaryColor: '#7A263A', secondaryColor: '#1BB1E7', tactics: 'Defensive',
    squad: [
      { id: 901, name: 'J. Bowen', position: 'DEL', rating: 82, value: 50, wage: 120000, morale: 'Contento', contractYears: 4 },
      { id: 902, name: 'M. Kudus', position: 'CEN', rating: 81, value: 50, wage: 90000, morale: 'Contento', contractYears: 5 },
      { id: 903, name: 'L. Paquetá', position: 'CEN', rating: 84, value: 65, wage: 150000, morale: 'Normal', contractYears: 3 },
      { id: 904, name: 'J. Ward-Prowse', position: 'CEN', rating: 82, value: 40, wage: 115000, morale: 'Contento', contractYears: 4 },
      { id: 905, name: 'A. Areola', position: 'POR', rating: 81, value: 20, wage: 120000, morale: 'Contento', contractYears: 3 },
      { id: 906, name: 'K. Zouma', position: 'DEF', rating: 80, value: 20, wage: 125000, morale: 'Normal', contractYears: 2 },
      { id: 907, name: 'E. Álvarez', position: 'CEN', rating: 80, value: 35, wage: 100000, morale: 'Contento', contractYears: 4 },
      { id: 908, name: 'N. Aguerd', position: 'DEF', rating: 79, value: 30, wage: 50000, morale: 'Normal', contractYears: 4 },
      { id: 909, name: 'Emerson', position: 'DEF', rating: 78, value: 18, wage: 95000, morale: 'Contento', contractYears: 3 },
      { id: 910, name: 'V. Coufal', position: 'DEF', rating: 78, value: 15, wage: 65000, morale: 'Contento', contractYears: 2 },
      { id: 911, name: 'T. Soucek', position: 'CEN', rating: 79, value: 30, wage: 65000, morale: 'Normal', contractYears: 3 },
      { id: 912, name: 'M. Antonio', position: 'DEL', rating: 78, value: 10, wage: 85000, morale: 'Normal', contractYears: 1 },
      { id: 913, name: 'S. Benrahma', position: 'DEL', rating: 78, value: 22, wage: 55000, morale: 'Descontento', contractYears: 3 },
      { id: 914, name: 'D. Ings', position: 'DEL', rating: 77, value: 10, wage: 125000, morale: 'Descontento', contractYears: 2 },
      { id: 915, name: 'L. Fabianski', position: 'POR', rating: 78, value: 3, wage: 65000, morale: 'Normal', contractYears: 1 },
      { id: 916, name: 'A. Ogbonna', position: 'DEF', rating: 76, value: 2, wage: 70000, morale: 'Normal', contractYears: 1 },
    ]
  },
  {
    id: 10, name: 'Brighton', logo: createTeamLogo(TEAM_LOGOS['Brighton'], 'Brighton'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 130, transferBudget: 45, tier: 'Mid', teamMorale: 'Normal',
    primaryColor: '#0057B8', secondaryColor: '#FFFFFF', tactics: 'Attacking',
    squad: [
      { id: 1001, name: 'K. Mitoma', position: 'CEN', rating: 81, value: 50, wage: 80000, morale: 'Contento', contractYears: 3 },
      { id: 1002, name: 'João Pedro', position: 'DEL', rating: 79, value: 45, wage: 65000, morale: 'Contento', contractYears: 4 },
      { id: 1003, name: 'P. Estupiñán', position: 'DEF', rating: 80, value: 35, wage: 70000, morale: 'Normal', contractYears: 4 },
      { id: 1004, name: 'L. Dunk', position: 'DEF', rating: 81, value: 25, wage: 80000, morale: 'Feliz', contractYears: 3 },
      { id: 1005, name: 'P. Groß', position: 'CEN', rating: 82, value: 20, wage: 65000, morale: 'Contento', contractYears: 2 },
      { id: 1006, name: 'S. March', position: 'CEN', rating: 80, value: 30, wage: 50000, morale: 'Normal', contractYears: 3 },
      { id: 1007, name: 'E. Ferguson', position: 'DEL', rating: 76, value: 60, wage: 40000, morale: 'Contento', contractYears: 5 },
      { id: 1008, name: 'B. Verbruggen', position: 'POR', rating: 76, value: 20, wage: 25000, morale: 'Contento', contractYears: 5 },
      { id: 1009, name: 'A. Fati', position: 'DEL', rating: 78, value: 30, wage: 160000, morale: 'Normal', contractYears: 1 },
      { id: 1010, name: 'B. Gilmour', position: 'CEN', rating: 77, value: 25, wage: 45000, morale: 'Contento', contractYears: 3 },
      { id: 1011, name: 'T. Lamptey', position: 'DEF', rating: 76, value: 18, wage: 50000, morale: 'Normal', contractYears: 2 },
      { id: 1012, name: 'J. Veltman', position: 'DEF', rating: 78, value: 10, wage: 55000, morale: 'Contento', contractYears: 2 },
      { id: 1013, name: 'D. Welbeck', position: 'DEL', rating: 77, value: 8, wage: 65000, morale: 'Normal', contractYears: 1 },
      { id: 1014, name: 'J. Steele', position: 'POR', rating: 74, value: 5, wage: 25000, morale: 'Normal', contractYears: 3 },
      { id: 1015, name: 'S. Adingra', position: 'DEL', rating: 75, value: 22, wage: 30000, morale: 'Contento', contractYears: 4 },
      { id: 1016, name: 'A. Webster', position: 'DEF', rating: 77, value: 15, wage: 50000, morale: 'Normal', contractYears: 2 },
    ]
  },
  {
    id: 11, name: 'Fulham', logo: createTeamLogo(TEAM_LOGOS['Fulham'], 'Fulham'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 110, transferBudget: 30, tier: 'Lower', teamMorale: 'Normal',
    primaryColor: '#000000', secondaryColor: '#CC0000', tactics: 'Balanced',
    squad: [
      { id: 1101, name: 'J. Palhinha', position: 'CEN', rating: 83, value: 55, wage: 90000, morale: 'Contento', contractYears: 3 },
      { id: 1102, name: 'A. Pereira', position: 'CEN', rating: 79, value: 30, wage: 65000, morale: 'Contento', contractYears: 3 },
      { id: 1103, name: 'B. Leno', position: 'POR', rating: 80, value: 15, wage: 80000, morale: 'Contento', contractYears: 2 },
      { id: 1104, name: 'Willian', position: 'DEL', rating: 79, value: 8, wage: 90000, morale: 'Contento', contractYears: 1 },
      { id: 1105, name: 'A. Iwobi', position: 'CEN', rating: 78, value: 28, wage: 80000, morale: 'Contento', contractYears: 4 },
      { id: 1106, name: 'T. Castagne', position: 'DEF', rating: 78, value: 20, wage: 65000, morale: 'Contento', contractYears: 4 },
      { id: 1107, name: 'H. Wilson', position: 'DEL', rating: 77, value: 20, wage: 45000, morale: 'Contento', contractYears: 3 },
      { id: 1108, name: 'T. Adarabioyo', position: 'DEF', rating: 77, value: 18, wage: 40000, morale: 'Normal', contractYears: 1 },
      { id: 1109, name: 'R. Jiménez', position: 'DEL', rating: 77, value: 12, wage: 85000, morale: 'Normal', contractYears: 2 },
      { id: 1110, name: 'H. Reed', position: 'CEN', rating: 77, value: 18, wage: 60000, morale: 'Contento', contractYears: 3 },
      { id: 1111, name: 'A. Robinson', position: 'DEF', rating: 76, value: 15, wage: 50000, morale: 'Contento', contractYears: 4 },
      { id: 1112, name: 'I. Diop', position: 'DEF', rating: 76, value: 14, wage: 60000, morale: 'Normal', contractYears: 4 },
      { id: 1113, name: 'S. Lukić', position: 'CEN', rating: 76, value: 15, wage: 50000, morale: 'Normal', contractYears: 3 },
      { id: 1114, name: 'T. Ream', position: 'DEF', rating: 75, value: 2, wage: 35000, morale: 'Contento', contractYears: 1 },
      { id: 1115, name: 'M. Rodák', position: 'POR', rating: 73, value: 3, wage: 20000, morale: 'Normal', contractYears: 2 },
      { id: 1116, name: 'C. Bassey', position: 'DEF', rating: 75, value: 16, wage: 70000, morale: 'Contento', contractYears: 4 },
    ]
  },
  {
    id: 12, name: 'Crystal Palace', logo: createTeamLogo(TEAM_LOGOS['Crystal Palace'], 'Crystal Palace'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 120, transferBudget: 35, tier: 'Lower', teamMorale: 'Normal',
    primaryColor: '#1B458F', secondaryColor: '#C4122E', tactics: 'Defensive',
    squad: [
      { id: 1201, name: 'E. Eze', position: 'CEN', rating: 81, value: 55, wage: 100000, morale: 'Feliz', contractYears: 4 },
      { id: 1202, name: 'M. Olise', position: 'DEL', rating: 80, value: 60, wage: 100000, morale: 'Feliz', contractYears: 4 },
      { id: 1203, name: 'M. Guéhi', position: 'DEF', rating: 80, value: 40, wage: 80000, morale: 'Contento', contractYears: 3 },
      { id: 1204, name: 'C. Doucouré', position: 'CEN', rating: 81, value: 35, wage: 65000, morale: 'Contento', contractYears: 4 },
      { id: 1205, name: 'S. Johnstone', position: 'POR', rating: 79, value: 15, wage: 40000, morale: 'Contento', contractYears: 3 },
      { id: 1206, name: 'J. Andersen', position: 'DEF', rating: 79, value: 30, wage: 80000, morale: 'Contento', contractYears: 3 },
      { id: 1207, name: 'J. Lerma', position: 'CEN', rating: 78, value: 20, wage: 100000, morale: 'Contento', contractYears: 3 },
      { id: 1208, name: 'O. Édouard', position: 'DEL', rating: 77, value: 20, wage: 90000, morale: 'Normal', contractYears: 3 },
      { id: 1209, name: 'T. Mitchell', position: 'DEF', rating: 77, value: 20, wage: 45000, morale: 'Contento', contractYears: 3 },
      { id: 1210, name: 'J. Schlupp', position: 'CEN', rating: 76, value: 10, wage: 55000, morale: 'Normal', contractYears: 2 },
      { id: 1211, name: 'J. Ward', position: 'DEF', rating: 75, value: 3, wage: 50000, morale: 'Contento', contractYears: 1 },
      { id: 1212, name: 'J. Ayew', position: 'DEL', rating: 76, value: 8, wage: 40000, morale: 'Normal', contractYears: 2 },
      { id: 1213, name: 'D. Henderson', position: 'POR', rating: 78, value: 12, wage: 80000, morale: 'Normal', contractYears: 4 },
      { id: 1214, name: 'C. Richards', position: 'DEF', rating: 74, value: 10, wage: 35000, morale: 'Normal', contractYears: 4 },
      { id: 1215, name: 'W. Hughes', position: 'CEN', rating: 75, value: 8, wage: 45000, morale: 'Normal', contractYears: 2 },
      { id: 1216, name: 'J.P. Mateta', position: 'DEL', rating: 75, value: 15, wage: 55000, morale: 'Normal', contractYears: 2 },
    ]
  },
  {
    id: 13, name: 'Brentford', logo: createTeamLogo(TEAM_LOGOS['Brentford'], 'Brentford'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 100, transferBudget: 30, tier: 'Lower', teamMorale: 'Normal',
    primaryColor: '#E30613', secondaryColor: '#F9F9F9', tactics: 'Attacking',
    squad: [
      { id: 1301, name: 'I. Toney', position: 'DEL', rating: 80, value: 50, wage: 100000, morale: 'Normal', contractYears: 1 },
      { id: 1302, name: 'B. Mbeumo', position: 'DEL', rating: 79, value: 40, wage: 70000, morale: 'Contento', contractYears: 3 },
      { id: 1303, name: 'R. Henry', position: 'DEF', rating: 77, value: 25, wage: 50000, morale: 'Normal', contractYears: 4 },
      { id: 1304, name: 'M. Flekken', position: 'POR', rating: 79, value: 18, wage: 35000, morale: 'Contento', contractYears: 4 },
      { id: 1305, name: 'M. Jensen', position: 'CEN', rating: 78, value: 25, wage: 45000, morale: 'Contento', contractYears: 3 },
      { id: 1306, name: 'C. Nørgaard', position: 'CEN', rating: 78, value: 22, wage: 50000, morale: 'Contento', contractYears: 3 },
      { id: 1307, name: 'E. Pinnock', position: 'DEF', rating: 77, value: 18, wage: 40000, morale: 'Contento', contractYears: 4 },
      { id: 1308, name: 'K. Schade', position: 'DEL', rating: 74, value: 20, wage: 35000, morale: 'Normal', contractYears: 5 },
      { id: 1309, name: 'V. Janelt', position: 'CEN', rating: 76, value: 18, wage: 30000, morale: 'Contento', contractYears: 3 },
      { id: 1310, name: 'N. Collins', position: 'DEF', rating: 76, value: 20, wage: 45000, morale: 'Normal', contractYears: 5 },
      { id: 1311, name: 'M. Damsgaard', position: 'CEN', rating: 75, value: 15, wage: 50000, morale: 'Normal', contractYears: 4 },
      { id: 1312, name: 'Y. Wissa', position: 'DEL', rating: 75, value: 16, wage: 40000, morale: 'Contento', contractYears: 3 },
      { id: 1313, name: 'K. Ajer', position: 'DEF', rating: 75, value: 15, wage: 35000, morale: 'Normal', contractYears: 3 },
      { id: 1314, name: 'M. Roerslev', position: 'DEF', rating: 74, value: 12, wage: 25000, morale: 'Normal', contractYears: 3 },
      { id: 1315, name: 'T. Strakosha', position: 'POR', rating: 76, value: 8, wage: 30000, morale: 'Normal', contractYears: 3 },
      { id: 1316, name: 'J. Dasilva', position: 'CEN', rating: 74, value: 10, wage: 28000, morale: 'Normal', contractYears: 2 },
    ]
  },
  {
    id: 14, name: 'Everton', logo: createTeamLogo(TEAM_LOGOS['Everton'], 'Everton'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 140, transferBudget: 25, tier: 'Lower', teamMorale: 'Normal',
    primaryColor: '#003399', secondaryColor: '#FFFFFF', tactics: 'Defensive',
    squad: [
      { id: 1401, name: 'J. Pickford', position: 'POR', rating: 82, value: 25, wage: 125000, morale: 'Contento', contractYears: 3 },
      { id: 1402, name: 'A. Onana', position: 'CEN', rating: 79, value: 50, wage: 100000, morale: 'Normal', contractYears: 4 },
      { id: 1403, name: 'J. Branthwaite', position: 'DEF', rating: 78, value: 45, wage: 75000, morale: 'Contento', contractYears: 3 },
      { id: 1404, name: 'D. Calvert-Lewin', position: 'DEL', rating: 79, value: 30, wage: 100000, morale: 'Normal', contractYears: 2 },
      { id: 1405, name: 'A. Doucouré', position: 'CEN', rating: 79, value: 20, wage: 120000, morale: 'Contento', contractYears: 2 },
      { id: 1406, name: 'J. Tarkowski', position: 'DEF', rating: 79, value: 15, wage: 100000, morale: 'Contento', contractYears: 2 },
      { id: 1407, name: 'D. McNeil', position: 'CEN', rating: 77, value: 25, wage: 45000, morale: 'Contento', contractYears: 4 },
      { id: 1408, name: 'I. Gueye', position: 'CEN', rating: 78, value: 8, wage: 80000, morale: 'Normal', contractYears: 1 },
      { id: 1409, name: 'V. Mykolenko', position: 'DEF', rating: 76, value: 20, wage: 32000, morale: 'Normal', contractYears: 4 },
      { id: 1410, name: 'J. Garner', position: 'CEN', rating: 76, value: 20, wage: 50000, morale: 'Contento', contractYears: 3 },
      { id: 1411, name: 'Beto', position: 'DEL', rating: 76, value: 18, wage: 50000, morale: 'Normal', contractYears: 4 },
      { id: 1412, name: 'J. Harrison', position: 'DEL', rating: 77, value: 20, wage: 90000, morale: 'Normal', contractYears: 1 },
      { id: 1413, name: 'A. Young', position: 'DEF', rating: 74, value: 1, wage: 40000, morale: 'Normal', contractYears: 1 },
      { id: 1414, name: 'S. Coleman', position: 'DEF', rating: 73, value: 1, wage: 55000, morale: 'Contento', contractYears: 1 },
      { id: 1415, name: 'A. Danjuma', position: 'DEL', rating: 78, value: 18, wage: 65000, morale: 'Descontento', contractYears: 1 },
      { id: 1416, name: 'J. Virginia', position: 'POR', rating: 68, value: 1, wage: 10000, morale: 'Normal', contractYears: 2 },
    ]
  },
  {
    id: 15, name: 'Nottm Forest', logo: createTeamLogo(TEAM_LOGOS['Nottingham Forest'], 'Nottingham Forest'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 90, transferBudget: 20, tier: 'Lower', teamMorale: 'Normal',
    primaryColor: '#DD0000', secondaryColor: '#FFFFFF', tactics: 'Balanced',
    squad: [
      { id: 1501, name: 'M. Gibbs-White', position: 'CEN', rating: 79, value: 40, wage: 80000, morale: 'Contento', contractYears: 4 },
      { id: 1502, name: 'Murillo', position: 'DEF', rating: 77, value: 35, wage: 50000, morale: 'Contento', contractYears: 5 },
      { id: 1503, name: 'Danilo', position: 'CEN', rating: 78, value: 30, wage: 60000, morale: 'Normal', contractYears: 4 },
      { id: 1504, name: 'T. Awoniyi', position: 'DEL', rating: 78, value: 25, wage: 50000, morale: 'Contento', contractYears: 4 },
      { id: 1505, name: 'O. Mangala', position: 'CEN', rating: 77, value: 22, wage: 55000, morale: 'Normal', contractYears: 3 },
      { id: 1506, name: 'N. Williams', position: 'DEF', rating: 75, value: 15, wage: 50000, morale: 'Normal', contractYears: 3 },
      { id: 1507, name: 'M. Sels', position: 'POR', rating: 77, value: 8, wage: 30000, morale: 'Contento', contractYears: 3 },
      { id: 1508, name: 'A. Elanga', position: 'DEL', rating: 75, value: 20, wage: 40000, morale: 'Contento', contractYears: 4 },
      { id: 1509, name: 'I. Sangaré', position: 'CEN', rating: 79, value: 30, wage: 75000, morale: 'Normal', contractYears: 4 },
      { id: 1510, name: 'W. Boly', position: 'DEF', rating: 76, value: 5, wage: 50000, morale: 'Normal', contractYears: 2 },
      { id: 1511, name: 'C. Hudson-Odoi', position: 'DEL', rating: 76, value: 18, wage: 80000, morale: 'Normal', contractYears: 3 },
      { id: 1512, name: 'H. Toffolo', position: 'DEF', rating: 74, value: 8, wage: 20000, morale: 'Normal', contractYears: 3 },
      { id: 1513, name: 'N. Domínguez', position: 'CEN', rating: 76, value: 16, wage: 60000, morale: 'Normal', contractYears: 4 },
      { id: 1514, name: 'C. Wood', position: 'DEL', rating: 75, value: 8, wage: 40000, morale: 'Contento', contractYears: 2 },
      { id: 1515, name: 'M. Turner', position: 'POR', rating: 76, value: 10, wage: 35000, morale: 'Descontento', contractYears: 4 },
      { id: 1516, name: 'S. Aurier', position: 'DEF', rating: 76, value: 6, wage: 40000, morale: 'Normal', contractYears: 1 },
    ]
  },
  {
    id: 16, name: 'Bournemouth', logo: createTeamLogo(TEAM_LOGOS['AFC Bournemouth'], 'AFC Bournemouth'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 85, transferBudget: 25, tier: 'Lower', teamMorale: 'Normal',
    primaryColor: '#DA291C', secondaryColor: '#000000', tactics: 'Attacking',
    squad: [
      { id: 1601, name: 'D. Solanke', position: 'DEL', rating: 80, value: 35, wage: 75000, morale: 'Contento', contractYears: 3 },
      { id: 1602, name: 'Neto', position: 'POR', rating: 80, value: 10, wage: 60000, morale: 'Contento', contractYears: 2 },
      { id: 1603, name: 'P. Billing', position: 'CEN', rating: 77, value: 20, wage: 65000, morale: 'Normal', contractYears: 3 },
      { id: 1604, name: 'M. Senesi', position: 'DEF', rating: 78, value: 22, wage: 50000, morale: 'Contento', contractYears: 4 },
      { id: 1605, name: 'L. Cook', position: 'CEN', rating: 77, value: 18, wage: 40000, morale: 'Contento', contractYears: 3 },
      { id: 1606, name: 'T. Adams', position: 'CEN', rating: 77, value: 20, wage: 55000, morale: 'Normal', contractYears: 4 },
      { id: 1607, name: 'A. Semenyo', position: 'DEL', rating: 75, value: 15, wage: 30000, morale: 'Contento', contractYears: 4 },
      { id: 1608, name: 'I. Zabarnyi', position: 'DEF', rating: 75, value: 20, wage: 40000, morale: 'Contento', contractYears: 5 },
      { id: 1609, name: 'M. Tavernier', position: 'CEN', rating: 76, value: 18, wage: 35000, morale: 'Normal', contractYears: 4 },
      { id: 1610, name: 'J. Kluivert', position: 'DEL', rating: 76, value: 18, wage: 80000, morale: 'Normal', contractYears: 4 },
      { id: 1611, name: 'M. Kerkez', position: 'DEF', rating: 75, value: 20, wage: 30000, morale: 'Contento', contractYears: 5 },
      { id: 1612, name: 'R. Christie', position: 'CEN', rating: 75, value: 12, wage: 35000, morale: 'Normal', contractYears: 2 },
      { id: 1613, name: 'L. Kelly', position: 'DEF', rating: 75, value: 12, wage: 30000, morale: 'Normal', contractYears: 1 },
      { id: 1614, name: 'M. Aarons', position: 'DEF', rating: 75, value: 15, wage: 60000, morale: 'Normal', contractYears: 4 },
      { id: 1615, name: 'A. Smith', position: 'DEF', rating: 74, value: 2, wage: 35000, morale: 'Contento', contractYears: 1 },
      { id: 1616, name: 'M. Travers', position: 'POR', rating: 73, value: 5, wage: 20000, morale: 'Normal', contractYears: 4 },
    ]
  },
  {
    id: 17, name: 'Wolves', logo: createTeamLogo(TEAM_LOGOS['Wolverhampton'], 'Wolverhampton'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 100, transferBudget: 30, tier: 'Lower', teamMorale: 'Normal',
    primaryColor: '#FDB913', secondaryColor: '#231F20', tactics: 'Balanced',
    squad: [
      { id: 1701, name: 'P. Neto', position: 'DEL', rating: 80, value: 45, wage: 90000, morale: 'Normal', contractYears: 3 },
      { id: 1702, name: 'M. Cunha', position: 'DEL', rating: 81, value: 55, wage: 100000, morale: 'Contento', contractYears: 4 },
      { id: 1703, name: 'C. Dawson', position: 'DEF', rating: 78, value: 5, wage: 55000, morale: 'Normal', contractYears: 1 },
      { id: 1704, name: 'José Sá', position: 'POR', rating: 81, value: 20, wage: 40000, morale: 'Contento', contractYears: 3 },
      { id: 1705, name: 'M. Kilman', position: 'DEF', rating: 78, value: 30, wage: 50000, morale: 'Contento', contractYears: 5 },
      { id: 1706, name: 'R. Aït-Nouri', position: 'DEF', rating: 77, value: 28, wage: 35000, morale: 'Contento', contractYears: 3 },
      { id: 1707, name: 'Hwang H.C.', position: 'DEL', rating: 78, value: 25, wage: 30000, morale: 'Contento', contractYears: 4 },
      { id: 1708, name: 'M. Lemina', position: 'CEN', rating: 78, value: 18, wage: 45000, morale: 'Contento', contractYears: 3 },
      { id: 1709, name: 'J. Gomes', position: 'CEN', rating: 76, value: 22, wage: 30000, morale: 'Contento', contractYears: 4 },
      { id: 1710, name: 'N. Semedo', position: 'DEF', rating: 79, value: 18, wage: 80000, morale: 'Normal', contractYears: 2 },
      { id: 1711, name: 'P. Sarabia', position: 'CEN', rating: 79, value: 15, wage: 90000, morale: 'Normal', contractYears: 2 },
      { id: 1712, name: 'B. Traoré', position: 'CEN', rating: 74, value: 10, wage: 20000, morale: 'Normal', contractYears: 4 },
      { id: 1713, name: 'Toti Gomes', position: 'DEF', rating: 74, value: 10, wage: 20000, morale: 'Normal', contractYears: 4 },
      { id: 1714, name: 'D. Bentley', position: 'POR', rating: 72, value: 2, wage: 25000, morale: 'Normal', contractYears: 2 },
      { id: 1715, name: 'S. Bueno', position: 'DEF', rating: 74, value: 8, wage: 30000, morale: 'Normal', contractYears: 4 },
      { id: 1716, name: 'J. Bellegarde', position: 'CEN', rating: 76, value: 15, wage: 45000, morale: 'Normal', contractYears: 4 },
    ]
  },
  {
    id: 18, name: 'Ipswich Town', logo: createTeamLogo(TEAM_LOGOS['Ipswich Town'], 'Ipswich Town'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 50, transferBudget: 15, tier: 'Lower', teamMorale: 'Contento',
    primaryColor: '#3A64A3', secondaryColor: '#FFFFFF', tactics: 'Defensive',
    squad: [
      { id: 1801, name: 'L. Davis', position: 'DEF', rating: 75, value: 10, wage: 25000, morale: 'Contento', contractYears: 2 },
      { id: 1802, name: 'C. Chaplin', position: 'CEN', rating: 74, value: 8, wage: 20000, morale: 'Contento', contractYears: 3 },
      { id: 1803, name: 'S. Morsy', position: 'CEN', rating: 73, value: 5, wage: 18000, morale: 'Feliz', contractYears: 2 },
      { id: 1804, name: 'W. Burns', position: 'CEN', rating: 72, value: 4, wage: 15000, morale: 'Contento', contractYears: 2 },
      { id: 1805, name: 'V. Hladky', position: 'POR', rating: 71, value: 3, wage: 10000, morale: 'Contento', contractYears: 3 },
      { id: 1806, name: 'L. Woolfenden', position: 'DEF', rating: 72, value: 4, wage: 12000, morale: 'Contento', contractYears: 3 },
      { id: 1807, name: 'C. Burgess', position: 'DEF', rating: 70, value: 2, wage: 8000, morale: 'Contento', contractYears: 2 },
      { id: 1808, name: 'N. Broadhead', position: 'DEL', rating: 71, value: 3, wage: 15000, morale: 'Contento', contractYears: 3 },
      { id: 1809, name: 'G. Hirst', position: 'DEL', rating: 70, value: 3, wage: 12000, morale: 'Normal', contractYears: 3 },
      { id: 1810, name: 'M. Luongo', position: 'CEN', rating: 71, value: 3, wage: 14000, morale: 'Contento', contractYears: 1 },
      { id: 1811, name: 'H. Clarke', position: 'DEF', rating: 69, value: 2, wage: 10000, morale: 'Normal', contractYears: 3 },
      { id: 1812, name: 'K. Moore', position: 'DEL', rating: 72, value: 4, wage: 25000, morale: 'Normal', contractYears: 1 },
      { id: 1813, name: 'A. Tuanzebe', position: 'DEF', rating: 70, value: 3, wage: 20000, morale: 'Normal', contractYears: 1 },
      { id: 1814, name: 'J. Taylor', position: 'CEN', rating: 68, value: 2, wage: 9000, morale: 'Normal', contractYears: 3 },
      { id: 1815, name: 'C. Walton', position: 'POR', rating: 68, value: 1, wage: 8000, morale: 'Normal', contractYears: 2 },
      { id: 1816, name: 'K. Jackson', position: 'DEL', rating: 67, value: 1, wage: 7000, morale: 'Normal', contractYears: 2 },
    ]
  },
  {
    id: 19, name: 'Leicester City', logo: createTeamLogo(TEAM_LOGOS['Leicester City'], 'Leicester City'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 70, transferBudget: 20, tier: 'Lower', teamMorale: 'Contento',
    primaryColor: '#0053A0', secondaryColor: '#FDB913', tactics: 'Balanced',
    squad: [
      { id: 1901, name: 'K. Dewsbury-Hall', position: 'CEN', rating: 78, value: 30, wage: 75000, morale: 'Contento', contractYears: 3 },
      { id: 1902, name: 'J. Vardy', position: 'DEL', rating: 79, value: 5, wage: 100000, morale: 'Feliz', contractYears: 1 },
      { id: 1903, name: 'R. Pereira', position: 'DEF', rating: 78, value: 15, wage: 80000, morale: 'Normal', contractYears: 2 },
      { id: 1904, name: 'W. Faes', position: 'DEF', rating: 77, value: 20, wage: 50000, morale: 'Contento', contractYears: 4 },
      { id: 1905, name: 'H. Winks', position: 'CEN', rating: 77, value: 18, wage: 90000, morale: 'Contento', contractYears: 4 },
      { id: 1906, name: 'M. Hermansen', position: 'POR', rating: 75, value: 12, wage: 25000, morale: 'Contento', contractYears: 4 },
      { id: 1907, name: 'K. Iheanacho', position: 'DEL', rating: 77, value: 15, wage: 80000, morale: 'Normal', contractYears: 1 },
      { id: 1908, name: 'P. Daka', position: 'DEL', rating: 75, value: 18, wage: 75000, morale: 'Normal', contractYears: 3 },
      { id: 1909, name: 'W. Ndidi', position: 'CEN', rating: 78, value: 20, wage: 75000, morale: 'Normal', contractYears: 1 },
      { id: 1910, name: 'J. Justin', position: 'DEF', rating: 75, value: 12, wage: 30000, morale: 'Normal', contractYears: 3 },
      { id: 1911, name: 'C. Coady', position: 'DEF', rating: 76, value: 8, wage: 45000, morale: 'Contento', contractYears: 2 },
      { id: 1912, name: 'S. Mavididi', position: 'DEL', rating: 76, value: 18, wage: 40000, morale: 'Contento', contractYears: 4 },
      { id: 1913, name: 'H. Souttar', position: 'DEF', rating: 74, value: 10, wage: 40000, morale: 'Descontento', contractYears: 4 },
      { id: 1914, name: 'D. Praet', position: 'CEN', rating: 76, value: 12, wage: 75000, morale: 'Descontento', contractYears: 2 },
      { id: 1915, name: 'D. Ward', position: 'POR', rating: 73, value: 3, wage: 35000, morale: 'Normal', contractYears: 3 },
      { id: 1916, name: 'Y. Akgün', position: 'DEL', rating: 74, value: 10, wage: 28000, morale: 'Normal', contractYears: 1 },
    ]
  },
  {
    id: 20, name: 'Southampton', logo: createTeamLogo(TEAM_LOGOS['Southampton'], 'Southampton'), leagueId: LeagueId.PREMIER_LEAGUE, budget: 60, transferBudget: 18, tier: 'Lower', teamMorale: 'Contento',
    primaryColor: '#D71920', secondaryColor: '#130C0E', tactics: 'Attacking',
    squad: [
      { id: 2001, name: 'K. Walker-Peters', position: 'DEF', rating: 77, value: 20, wage: 50000, morale: 'Contento', contractYears: 2 },
      { id: 2002, name: 'A. Armstrong', position: 'DEL', rating: 76, value: 18, wage: 65000, morale: 'Contento', contractYears: 3 },
      { id: 2003, name: 'T. Harwood-Bellis', position: 'DEF', rating: 75, value: 15, wage: 45000, morale: 'Contento', contractYears: 4 },
      { id: 2004, name: 'G. Bazunu', position: 'POR', rating: 72, value: 10, wage: 40000, morale: 'Contento', contractYears: 4 },
      { id: 2005, name: 'F. Downes', position: 'CEN', rating: 74, value: 8, wage: 25000, morale: 'Contento', contractYears: 3 },
      { id: 2006, name: 'J. Aribo', position: 'CEN', rating: 75, value: 12, wage: 70000, morale: 'Normal', contractYears: 3 },
      { id: 2007, name: 'C. Alcaraz', position: 'CEN', rating: 74, value: 15, wage: 30000, morale: 'Normal', contractYears: 4 },
      { id: 2008, name: 'J. Bednarek', position: 'DEF', rating: 74, value: 10, wage: 60000, morale: 'Normal', contractYears: 3 },
      { id: 2009, name: 'S. Edozie', position: 'DEL', rating: 71, value: 8, wage: 20000, morale: 'Contento', contractYears: 4 },
      { id: 2010, name: 'R. Fraser', position: 'DEL', rating: 75, value: 8, wage: 42000, morale: 'Normal', contractYears: 1 },
      { id: 2011, name: 'S. Armstrong', position: 'CEN', rating: 74, value: 6, wage: 65000, morale: 'Normal', contractYears: 1 },
      { id: 2012, name: 'S. Mara', position: 'DEL', rating: 70, value: 7, wage: 35000, morale: 'Normal', contractYears: 4 },
      { id: 2013, name: 'J. Stephens', position: 'DEF', rating: 71, value: 3, wage: 50000, morale: 'Contento', contractYears: 2 },
      { id: 2014, name: 'A. McCarthy', position: 'POR', rating: 72, value: 2, wage: 50000, morale: 'Normal', contractYears: 1 },
      { id: 2015, name: 'W. Smallbone', position: 'CEN', rating: 70, value: 4, wage: 15000, morale: 'Contento', contractYears: 3 },
      { id: 2016, name: 'K. Sulemana', position: 'DEL', rating: 74, value: 18, wage: 65000, morale: 'Normal', contractYears: 4 },
    ]
  },
];

// By separating the sort from the array declaration, TypeScript can correctly
// apply contextual typing to the array literal, avoiding potential type errors.
TEAMS.sort((a, b) => a.name.localeCompare(b.name));
