/**
 * Vector SVG badges and club logos from Community Data Packs
 * Source: https://github.com/Extremer12/community-data-packs (Extremer12/community-data-packs@main)
 * CDN: jsDelivr
 * 
 * Folders:
 * - Argentina/primera_division/
 * - Argentina/primera_nacional/
 * - Premier League/
 * - Championship/
 */

export const COMMUNITY_PACK_CDN = 'https://cdn.jsdelivr.net/gh/Extremer12/community-data-packs@main';
export const ARG_PACK_CDN = COMMUNITY_PACK_CDN; // Backwards-compatible alias

export const ARG_COMPETITION_LOGOS: Record<string, string> = {
    LIGA_ARGENTINA: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_argentina-primera-division.football-logos.cc.svg`,
    PRIMERA_NACIONAL: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_primera-nacional.football-logos.cc.svg`,
    PREMIER_LEAGUE: `${COMMUNITY_PACK_CDN}/Premier%20League/england_english-premier-league.football-logos.cc.svg`,
    CHAMPIONSHIP: `${COMMUNITY_PACK_CDN}/Championship/england_efl-championship.football-logos.cc.svg`,
    SERIE_A: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_serie-a.football-logos.cc.svg`,
    SERIE_B_ITA: `${COMMUNITY_PACK_CDN}/Serie%20B/italy_serie-b.football-logos.cc.svg`,
    BRASILEIRAO: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_brazilian-serie-a.football-logos.cc.svg`,
    SERIE_A_BR: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_brazilian-serie-a.football-logos.cc.svg`,
    SERIE_B_BR: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_brazilian-serie-b.football-logos.cc.svg`,
    LA_LIGA: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_la-liga.football-logos.cc.svg`,
    SEGUNDA_DIVISION_ESP: `${COMMUNITY_PACK_CDN}/La%20Liga%202/spain_la-liga-2.football-logos.cc.svg`,
    BUNDESLIGA: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_bundesliga.football-logos.cc.svg`,
    ZWEITE_BUNDESLIGA: `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_2-bundesliga.football-logos.cc.svg`,
    LIGUE_1: `${COMMUNITY_PACK_CDN}/Ligue%201/france_ligue-1.football-logos.cc.svg`,
    LIGUE_2: `${COMMUNITY_PACK_CDN}/Ligue%202/france_ligue-2.football-logos.cc.svg`,
    'liga-argentina': `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_argentina-primera-division.football-logos.cc.svg`,
    'primera-nacional': `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_primera-nacional.football-logos.cc.svg`,
    'premier-league': `${COMMUNITY_PACK_CDN}/Premier%20League/england_english-premier-league.football-logos.cc.svg`,
    'championship': `${COMMUNITY_PACK_CDN}/Championship/england_efl-championship.football-logos.cc.svg`,
    'serie-a': `${COMMUNITY_PACK_CDN}/Serie%20A/italy_serie-a.football-logos.cc.svg`,
    'serie-b-ita': `${COMMUNITY_PACK_CDN}/Serie%20B/italy_serie-b.football-logos.cc.svg`,
    'brasileirao': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_brazilian-serie-a.football-logos.cc.svg`,
    'serie-a-br': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_brazilian-serie-a.football-logos.cc.svg`,
    'serie-b-br': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_brazilian-serie-b.football-logos.cc.svg`,
    'la-liga': `${COMMUNITY_PACK_CDN}/La%20Liga/spain_la-liga.football-logos.cc.svg`,
    'la-liga-2': `${COMMUNITY_PACK_CDN}/La%20Liga%202/spain_la-liga-2.football-logos.cc.svg`,
    'segunda-division-esp': `${COMMUNITY_PACK_CDN}/La%20Liga%202/spain_la-liga-2.football-logos.cc.svg`,
    'bundesliga': `${COMMUNITY_PACK_CDN}/Bundesliga/germany_bundesliga.football-logos.cc.svg`,
    'zweite-bundesliga': `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_2-bundesliga.football-logos.cc.svg`,
    '2-bundesliga': `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_2-bundesliga.football-logos.cc.svg`,
    'bundesliga-2': `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_2-bundesliga.football-logos.cc.svg`,
    'ligue-1': `${COMMUNITY_PACK_CDN}/Ligue%201/france_ligue-1.football-logos.cc.svg`,
    'ligue-2': `${COMMUNITY_PACK_CDN}/Ligue%202/france_ligue-2.football-logos.cc.svg`,
};

export const ARG_CLUB_LOGOS_BY_ID: Record<number | string, string> = {
    // ==========================================
    // Primera División (IDs 701-733)
    // ==========================================
    701: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_boca-juniors.football-logos.cc.svg`,
    702: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_river-plate.football-logos.cc.svg`,
    703: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_racing-club.football-logos.cc.svg`,
    704: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_independiente.football-logos.cc.svg`,
    705: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_san-lorenzo-de-almagro.football-logos.cc.svg`,
    706: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_estudiantes-de-la-plata.football-logos.cc.svg`,
    707: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_velez-sarsfield.football-logos.cc.svg`,
    708: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_ca-huracan.football-logos.cc.svg`,
    709: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_rosario-central.football-logos.cc.svg`,
    710: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_newells-old-boys.football-logos.cc.svg`,
    711: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_talleres.football-logos.cc.svg`,
    712: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_atletico-tucuman.football-logos.cc.svg`,
    714: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_defensa-y-justicia.football-logos.cc.svg`,
    715: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_lanus.football-logos.cc.svg`,
    716: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_belgrano.football-logos.cc.svg`,
    717: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_instituto-cordoba.football-logos.cc.svg`,
    718: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_sarmiento.football-logos.cc.svg`,
    719: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_central-cordoba.football-logos.cc.svg`,
    720: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_barracas-central.football-logos.cc.svg`,
    721: `${COMMUNITY_PACK_CDN}/otros%20Argentina/argentina_godoy-cruz.football-logos.cc.svg`,
    722: `${COMMUNITY_PACK_CDN}/otros%20Argentina/argentina_platense.football-logos.cc.svg`,
    723: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_tigre.football-logos.cc.svg`,
    724: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_union.football-logos.cc.svg`,
    726: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_argeninos-juniors.football-logos.cc.svg`,
    727: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_deportivo-riestra.football-logos.cc.svg`,
    728: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_gimnasia-y-esgrima.football-logos.cc.svg`,
    729: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_gimnasia-lp.football-logos.cc.svg`,
    730: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_banfield.football-logos.cc.svg`,
    731: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_independiente-rivadavia.football-logos.cc.svg`,
    732: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_aldosivi.football-logos.cc.svg`,
    733: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_estudiantes-de-rio-cuarto.football-logos.cc.svg`,

    // ==========================================
    // Primera Nacional (IDs 750+)
    // ==========================================
    752: `${COMMUNITY_PACK_CDN}/otros%20Argentina/argentina_san-martin-san-juan.football-logos.cc.svg`,
    753: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_chaco-for-ever.football-logos.cc.svg`,
    754: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_nueva-chicago.football-logos.cc.svg`,
    755: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_almagro.football-logos.cc.svg`,
    756: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_all-boys.football-logos.cc.svg`,
    757: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_estudiantes-de-buenos-aires.football-logos.cc.svg`,
    759: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_deportivo-moron.football-logos.cc.svg`,
    760: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_ferro-carril-oeste.football-logos.cc.svg`,
    761: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_agropecuario-argentino.football-logos.cc.svg`,
    762: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_almirante-brown.football-logos.cc.svg`,
    764: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_chacarita-juniors.football-logos.cc.svg`,
    765: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_temperley.football-logos.cc.svg`,
    766: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_mitre-santiago-del-estero.football-logos.cc.svg`,
    767: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_colon-santa-fe.football-logos.cc.svg`,
    770: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_quilmes.football-logos.cc.svg`,
    771: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_central-norte.football-logos.cc.svg`,
    772: `${COMMUNITY_PACK_CDN}/otros%20Argentina/argentina_guillermo-brown.football-logos.cc.svg`,
    773: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_defensores-de-belgrano.football-logos.cc.svg`,
    774: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_deportivo-madryn.football-logos.cc.svg`,
    775: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_los-andes.football-logos.cc.svg`,
    776: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_racing.football-logos.cc.svg`,
    777: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_san-miguel.football-logos.cc.svg`,
    778: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_san-telmo.football-logos.cc.svg`,
    779: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_atletico-atlanta.football-logos.cc.svg`,
    781: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_colegiales.football-logos.cc.svg`,
    782: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_deportivo-maipu.football-logos.cc.svg`,
    784: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_gimnasia-de-jujuy.football-logos.cc.svg`,
    785: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_gimnasia-y-tiro.football-logos.cc.svg`,
    786: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_guemes.football-logos.cc.svg`,
    787: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_patronato.football-logos.cc.svg`,
    788: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_san-martin-tucuman.football-logos.cc.svg`,
    789: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_tristan-suarez.football-logos.cc.svg`,
    790: `${COMMUNITY_PACK_CDN}/otros%20Argentina/argentina_villa-dalmine.football-logos.cc.svg`,
    791: `${COMMUNITY_PACK_CDN}/otros%20Argentina/argentina_villa-mitre.football-logos.cc.svg`,
    792: `${COMMUNITY_PACK_CDN}/otros%20Argentina/argentina_douglas-haig.football-logos.cc.svg`,
    793: `${COMMUNITY_PACK_CDN}/otros%20Argentina/argentina_deportivo-merlo.football-logos.cc.svg`,
    794: `${COMMUNITY_PACK_CDN}/otros%20Argentina/argentina_atletico-policial.football-logos.cc.svg`,
    795: `${COMMUNITY_PACK_CDN}/otros%20Argentina/argentina_libertad-sunchales.football-logos.cc.svg`,
    796: `${COMMUNITY_PACK_CDN}/otros%20Argentina/argentina_racing-de-olavarria.football-logos.cc.svg`,
    797: `${COMMUNITY_PACK_CDN}/otros%20Argentina/argentina_sportivo-desamparados.football-logos.cc.svg`,

    // ==========================================
    // Premier League (IDs 1-20)
    // ==========================================
    1: `${COMMUNITY_PACK_CDN}/Premier%20League/england_arsenal.football-logos.cc.svg`,
    2: `${COMMUNITY_PACK_CDN}/Premier%20League/england_aston-villa.football-logos.cc.svg`,
    3: `${COMMUNITY_PACK_CDN}/Premier%20League/england_chelsea.football-logos.cc.svg`,
    4: `${COMMUNITY_PACK_CDN}/Premier%20League/england_liverpool.football-logos.cc.svg`,
    5: `${COMMUNITY_PACK_CDN}/Premier%20League/england_manchester-city.football-logos.cc.svg`,
    6: `${COMMUNITY_PACK_CDN}/Premier%20League/england_manchester-united.football-logos.cc.svg`,
    7: `${COMMUNITY_PACK_CDN}/Premier%20League/england_newcastle.football-logos.cc.svg`,
    8: `${COMMUNITY_PACK_CDN}/Premier%20League/england_tottenham.football-logos.cc.svg`,
    9: `${COMMUNITY_PACK_CDN}/Championship/england_west-ham.football-logos.cc.svg`,
    10: `${COMMUNITY_PACK_CDN}/Premier%20League/england_brighton.football-logos.cc.svg`,
    11: `${COMMUNITY_PACK_CDN}/Premier%20League/england_fulham.football-logos.cc.svg`,
    12: `${COMMUNITY_PACK_CDN}/Premier%20League/england_crystal-palace.football-logos.cc.svg`,
    13: `${COMMUNITY_PACK_CDN}/Premier%20League/england_brentford.football-logos.cc.svg`,
    14: `${COMMUNITY_PACK_CDN}/Premier%20League/england_everton.football-logos.cc.svg`,
    15: `${COMMUNITY_PACK_CDN}/Premier%20League/england_nottingham-forest.football-logos.cc.svg`,
    16: `${COMMUNITY_PACK_CDN}/Premier%20League/england_bournemouth.football-logos.cc.svg`,
    17: `${COMMUNITY_PACK_CDN}/Championship/england_wolves.football-logos.cc.svg`,
    18: `${COMMUNITY_PACK_CDN}/Premier%20League/england_ipswich.football-logos.cc.svg`,
    19: `${COMMUNITY_PACK_CDN}/Premier%20League/england_english-premier-league.football-logos.cc.svg`,
    20: `${COMMUNITY_PACK_CDN}/Championship/england_southampton.football-logos.cc.svg`,

    // ==========================================
    // Championship (IDs 101-124)
    // ==========================================
    101: `${COMMUNITY_PACK_CDN}/Premier%20League/england_leeds-united.football-logos.cc.svg`,
    102: `${COMMUNITY_PACK_CDN}/Championship/england_burnley.football-logos.cc.svg`,
    103: `${COMMUNITY_PACK_CDN}/Championship/england_luton.football-logos.cc.svg`,
    104: `${COMMUNITY_PACK_CDN}/Championship/england_sheffield-united.football-logos.cc.svg`,
    105: `${COMMUNITY_PACK_CDN}/Championship/england_west-bromwich-albion.football-logos.cc.svg`,
    106: `${COMMUNITY_PACK_CDN}/Championship/england_norwich-city.football-logos.cc.svg`,
    107: `${COMMUNITY_PACK_CDN}/Premier%20League/england_hull-city.football-logos.cc.svg`,
    108: `${COMMUNITY_PACK_CDN}/Championship/england_coventry.football-logos.cc.svg`,
    109: `${COMMUNITY_PACK_CDN}/Championship/england_middlesbrough.football-logos.cc.svg`,
    110: `${COMMUNITY_PACK_CDN}/Championship/england_preston-north-end.football-logos.cc.svg`,
    111: `${COMMUNITY_PACK_CDN}/Championship/england_cardiff-city.football-logos.cc.svg`,
    112: `${COMMUNITY_PACK_CDN}/Championship/england_bristol-city.football-logos.cc.svg`,
    113: `${COMMUNITY_PACK_CDN}/Premier%20League/england_sunderland.football-logos.cc.svg`,
    114: `${COMMUNITY_PACK_CDN}/Championship/england_swansea-city.football-logos.cc.svg`,
    115: `${COMMUNITY_PACK_CDN}/Championship/england_watford.football-logos.cc.svg`,
    116: `${COMMUNITY_PACK_CDN}/Championship/england_millwall.football-logos.cc.svg`,
    117: `${COMMUNITY_PACK_CDN}/Championship/england_queens-park-rangers.football-logos.cc.svg`,
    118: `${COMMUNITY_PACK_CDN}/Championship/england_stoke-city.football-logos.cc.svg`,
    119: `${COMMUNITY_PACK_CDN}/Championship/england_blackburn-rovers.football-logos.cc.svg`,
    120: `${COMMUNITY_PACK_CDN}/Championship/england_sheffield-wednesday.football-logos.cc.svg`,
    121: `${COMMUNITY_PACK_CDN}/Championship/england_plymouth.football-logos.cc.svg`,
    122: `${COMMUNITY_PACK_CDN}/Championship/england_portsmouth.football-logos.cc.svg`,
    123: `${COMMUNITY_PACK_CDN}/Championship/england_derby-county.football-logos.cc.svg`,
    124: `${COMMUNITY_PACK_CDN}/Championship/england_oxford.football-logos.cc.svg`,
    // ==========================================
    // Serie A (IDs 501-520)
    // ==========================================
    501: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_inter.football-logos.cc.svg`,
    502: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_milan.football-logos.cc.svg`,
    503: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_juventus.football-logos.cc.svg`,
    504: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_roma.football-logos.cc.svg`,
    505: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_napoli.football-logos.cc.svg`,
    506: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_atalanta.football-logos.cc.svg`,
    507: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_lazio.football-logos.cc.svg`,
    508: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_fiorentina.football-logos.cc.svg`,
    509: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_torino.football-logos.cc.svg`,
    510: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_bologna.football-logos.cc.svg`,
    511: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_genoa.football-logos.cc.svg`,
    512: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_monza.football-logos.cc.svg`,
    513: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_lecce.football-logos.cc.svg`,
    514: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_udinese.football-logos.cc.svg`,
    515: `${COMMUNITY_PACK_CDN}/Serie%20B/italy_verona.football-logos.cc.svg`,
    516: `${COMMUNITY_PACK_CDN}/Serie%20B/italy_empoli.football-logos.cc.svg`,
    517: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_cagliari.football-logos.cc.svg`,
    518: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_como-1907.football-logos.cc.svg`,
    519: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_parma.football-logos.cc.svg`,
    520: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_venezia.football-logos.cc.svg`,

    // ==========================================
    // Serie B Italiana (IDs 961-978)
    // ==========================================
    963: `${COMMUNITY_PACK_CDN}/Serie%20B/italy_palermo.football-logos.cc.svg`,
    965: `${COMMUNITY_PACK_CDN}/Serie%20B/italy_catanzaro.football-logos.cc.svg`,
    967: `${COMMUNITY_PACK_CDN}/Serie%20B/italy_cremonese.football-logos.cc.svg`,
    968: `${COMMUNITY_PACK_CDN}/Serie%20B/italy_modena.football-logos.cc.svg`,
    969: `${COMMUNITY_PACK_CDN}/Serie%20B/italy_cesena.football-logos.cc.svg`,
    971: `${COMMUNITY_PACK_CDN}/Serie%20B/italy_pisa.football-logos.cc.svg`,
    973: `${COMMUNITY_PACK_CDN}/Serie%20B/italy_suditrol.football-logos.cc.svg`,
    974: `${COMMUNITY_PACK_CDN}/Serie%20B/italy_mantova-1911.football-logos.cc.svg`,
    975: `${COMMUNITY_PACK_CDN}/Serie%20B/italy_carrarese.football-logos.cc.svg`,
    977: `${COMMUNITY_PACK_CDN}/Serie%20B/italy_juve-stabia.football-logos.cc.svg`,
    978: `${COMMUNITY_PACK_CDN}/Serie%20A/italy_frosinone.football-logos.cc.svg`,

    // ==========================================
    // Brasileirão Serie A (IDs 801-820)
    // ==========================================
    801: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_flamengo.football-logos.cc.svg`,
    802: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_palmeiras.football-logos.cc.svg`,
    803: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_sao-paulo.football-logos.cc.svg`,
    804: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_corinthians.football-logos.cc.svg`,
    805: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_santos.football-logos.cc.svg`,
    806: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_gremio.football-logos.cc.svg`,
    807: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_internacional.football-logos.cc.svg`,
    808: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_atletico-mineiro.football-logos.cc.svg`,
    809: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_fluminense.football-logos.cc.svg`,
    810: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_botafogo.football-logos.cc.svg`,
    811: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_vasco-da-gama.football-logos.cc.svg`,
    812: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_cruzeiro.football-logos.cc.svg`,
    813: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_bahia.football-logos.cc.svg`,
    814: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_fortaleza.football-logos.cc.svg`,
    815: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_ceara.football-logos.cc.svg`,
    816: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_athletico-paranaense.football-logos.cc.svg`,
    817: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_coritiba.football-logos.cc.svg`,
    818: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_rb-bragantino.football-logos.cc.svg`,
    819: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_america-mineiro.football-logos.cc.svg`,
    820: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_cuiaba.football-logos.cc.svg`,

    // ==========================================
    // Brasileirão Serie B (IDs 851-870)
    // ==========================================
    851: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_goias.football-logos.cc.svg`,
    852: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_sport-recife.football-logos.cc.svg`,
    853: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_ponte-preta.football-logos.cc.svg`,
    855: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_santos.football-logos.cc.svg`,
    856: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_crb.football-logos.cc.svg`,
    857: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_novorizontino.football-logos.cc.svg`,
    858: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_operario-ferroviario.football-logos.cc.svg`,
    860: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_botafogo-sp.football-logos.cc.svg`,
    861: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_londrina.football-logos.cc.svg`,
    862: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_chapecoense.football-logos.cc.svg`,
    865: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_mirassol.football-logos.cc.svg`,
    867: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_atletico-goianiense.football-logos.cc.svg`,
    868: `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_juventude.football-logos.cc.svg`,

    // ==========================================
    // La Liga Española (IDs 201-220)
    // ==========================================
    201: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_real-madrid.football-logos.cc.svg`,
    202: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_barcelona.football-logos.cc.svg`,
    203: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_atletico-madrid.football-logos.cc.svg`,
    204: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_athletic-club.football-logos.cc.svg`,
    205: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_real-sociedad.football-logos.cc.svg`,
    206: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_real-betis.football-logos.cc.svg`,
    207: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_girona.football-logos.cc.svg`,
    208: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_villarreal.football-logos.cc.svg`,
    209: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_valencia.football-logos.cc.svg`,
    210: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_sevilla.football-logos.cc.svg`,
    211: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_celta.football-logos.cc.svg`,
    212: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_osasuna.football-logos.cc.svg`,
    213: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_getafe.football-logos.cc.svg`,
    214: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_mallorca.football-logos.cc.svg`,
    215: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_rayo-vallecano.football-logos.cc.svg`,
    216: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_las-palmas.football-logos.cc.svg`,
    217: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_alaves.football-logos.cc.svg`,
    218: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_leganes.football-logos.cc.svg`,
    219: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_valladolid.football-logos.cc.svg`,
    220: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_espanyol.football-logos.cc.svg`,

    // ==========================================
    // Segunda División Española (IDs 901-922)
    // ==========================================
    901: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_elche.football-logos.cc.svg`,
    902: `${COMMUNITY_PACK_CDN}/La%20Liga%202/spain_sporting-gijon.football-logos.cc.svg`,
    903: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_malaga.football-logos.cc.svg`,
    904: `${COMMUNITY_PACK_CDN}/La%20Liga%202/spain_zaragoza.football-logos.cc.svg`,
    905: `${COMMUNITY_PACK_CDN}/La%20Liga%202/spain_tenerife.football-logos.cc.svg`,
    906: `${COMMUNITY_PACK_CDN}/La%20Liga%202/spain_cartagena.football-logos.cc.svg`,
    907: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_racing.football-logos.cc.svg`,
    908: `${COMMUNITY_PACK_CDN}/La%20Liga%202/spain_andorra.football-logos.cc.svg`,
    909: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_villarreal.football-logos.cc.svg`,
    910: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_espanyol.football-logos.cc.svg`,
    911: `${COMMUNITY_PACK_CDN}/La%20Liga%202/spain_almeria.football-logos.cc.svg`,
    912: `${COMMUNITY_PACK_CDN}/La%20Liga%202/spain_mirandes.football-logos.cc.svg`,
    913: `${COMMUNITY_PACK_CDN}/La%20Liga%202/spain_burgos.football-logos.cc.svg`,
    914: `${COMMUNITY_PACK_CDN}/La%20Liga%202/spain_racing-ferrol.football-logos.cc.svg`,
    915: `${COMMUNITY_PACK_CDN}/La%20Liga%202/spain_eldense.football-logos.cc.svg`,
    916: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_levante.football-logos.cc.svg`,
    917: `${COMMUNITY_PACK_CDN}/La%20Liga%202/spain_castellon.football-logos.cc.svg`,
    918: `${COMMUNITY_PACK_CDN}/La%20Liga%202/spain_cordoba.football-logos.cc.svg`,
    919: `${COMMUNITY_PACK_CDN}/La%20Liga%202/spain_oviedo.football-logos.cc.svg`,
    920: `${COMMUNITY_PACK_CDN}/La%20Liga%202/spain_huesca.football-logos.cc.svg`,
    921: `${COMMUNITY_PACK_CDN}/La%20Liga%202/spain_eibar.football-logos.cc.svg`,
    922: `${COMMUNITY_PACK_CDN}/La%20Liga/spain_valladolid.football-logos.cc.svg`,

    // ==========================================
    // Bundesliga Alemana (IDs 401-418)
    // ==========================================
    401: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_bayern-munchen.football-logos.cc.svg`,
    402: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_borussia-dortmund.football-logos.cc.svg`,
    403: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_bayer-leverkusen.football-logos.cc.svg`,
    404: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_rb-leipzig.football-logos.cc.svg`,
    405: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_eintracht-frankfurt.football-logos.cc.svg`,
    406: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_vfb-stuttgart.football-logos.cc.svg`,
    407: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_freiburg.football-logos.cc.svg`,
    408: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_hoffenheim.football-logos.cc.svg`,
    409: `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_fc-heidenheim.football-logos.cc.svg`,
    410: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_werder-bremen.football-logos.cc.svg`,
    411: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_augsburg.football-logos.cc.svg`,
    412: `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_wolfsburg.football-logos.cc.svg`,
    413: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_mainz-05.football-logos.cc.svg`,
    414: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_borussia-monchengladbach.football-logos.cc.svg`,
    415: `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_vfl-bochum.football-logos.cc.svg`,
    416: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_union-berlin.football-logos.cc.svg`,
    417: `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_st-pauli.football-logos.cc.svg`,
    418: `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_holstein-kiel.football-logos.cc.svg`,

    // ==========================================
    // 2. Bundesliga Alemana (IDs 931-948)
    // ==========================================
    931: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_hamburger-sv.football-logos.cc.svg`,
    932: `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_hannover-96.football-logos.cc.svg`,
    933: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_schalke-04.football-logos.cc.svg`,
    935: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_paderborn.football-logos.cc.svg`,
    936: `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_fc-kaiserslautern.football-logos.cc.svg`,
    937: `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_fc-nurnberg.football-logos.cc.svg`,
    938: `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_hertha-bsc.football-logos.cc.svg`,
    939: `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_spvgg-greuther-furth.football-logos.cc.svg`,
    940: `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_eintracht-braunschweig.football-logos.cc.svg`,
    941: `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_darmstadt.football-logos.cc.svg`,
    942: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_koln.football-logos.cc.svg`,
    944: `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_karlsruher.football-logos.cc.svg`,
    947: `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_1-fc-magdeburg.football-logos.cc.svg`,
    948: `${COMMUNITY_PACK_CDN}/Bundesliga/germany_sv-elversberg.football-logos.cc.svg`,

    // ==========================================
    // Ligue 1 Francesa (IDs 601-618)
    // ==========================================
    601: `${COMMUNITY_PACK_CDN}/Ligue%201/france_paris-saint-germain.football-logos.cc.svg`,
    602: `${COMMUNITY_PACK_CDN}/Ligue%201/france_marseille.football-logos.cc.svg`,
    603: `${COMMUNITY_PACK_CDN}/Ligue%201/france_as-monaco.football-logos.cc.svg`,
    604: `${COMMUNITY_PACK_CDN}/Ligue%201/france_rennes.football-logos.cc.svg`,
    605: `${COMMUNITY_PACK_CDN}/Ligue%201/france_lille.football-logos.cc.svg`,
    606: `${COMMUNITY_PACK_CDN}/Ligue%201/france_nice.football-logos.cc.svg`,
    607: `${COMMUNITY_PACK_CDN}/Ligue%201/france_lyon.football-logos.cc.svg`,
    608: `${COMMUNITY_PACK_CDN}/Ligue%201/france_rc-lens.football-logos.cc.svg`,
    609: `${COMMUNITY_PACK_CDN}/Ligue%201/france_brest.football-logos.cc.svg`,
    610: `${COMMUNITY_PACK_CDN}/Ligue%201/france_ligue-1.football-logos.cc.svg`,
    611: `${COMMUNITY_PACK_CDN}/Ligue%201/france_toulouse.football-logos.cc.svg`,
    612: `${COMMUNITY_PACK_CDN}/Ligue%201/france_ligue-1.football-logos.cc.svg`,
    613: `${COMMUNITY_PACK_CDN}/Ligue%201/france_ligue-1.football-logos.cc.svg`,
    614: `${COMMUNITY_PACK_CDN}/Ligue%201/france_ligue-1.football-logos.cc.svg`,
    615: `${COMMUNITY_PACK_CDN}/Ligue%201/france_rc-strasbourg-alsace.football-logos.cc.svg`,
    616: `${COMMUNITY_PACK_CDN}/Ligue%201/france_ligue-1.football-logos.cc.svg`,
    617: `${COMMUNITY_PACK_CDN}/Ligue%201/france_ligue-1.football-logos.cc.svg`,
    618: `${COMMUNITY_PACK_CDN}/Ligue%201/france_le-havre-ac.football-logos.cc.svg`,

    // ==========================================
    // Ligue 2 Francesa (IDs 651-670)
    // ==========================================
    651: `${COMMUNITY_PACK_CDN}/Ligue%202/france_ligue-2.football-logos.cc.svg`,
    652: `${COMMUNITY_PACK_CDN}/Ligue%202/france_ligue-2.football-logos.cc.svg`,
    653: `${COMMUNITY_PACK_CDN}/Ligue%202/france_ligue-2.football-logos.cc.svg`,
    654: `${COMMUNITY_PACK_CDN}/Ligue%202/france_paris-fc.football-logos.cc.svg`,
    655: `${COMMUNITY_PACK_CDN}/Ligue%202/france_ligue-2.football-logos.cc.svg`,
    656: `${COMMUNITY_PACK_CDN}/Ligue%202/france_ligue-2.football-logos.cc.svg`,
    657: `${COMMUNITY_PACK_CDN}/Ligue%202/france_troyes.football-logos.cc.svg`,
    658: `${COMMUNITY_PACK_CDN}/Ligue%202/france_ligue-2.football-logos.cc.svg`,
    659: `${COMMUNITY_PACK_CDN}/Ligue%202/france_auxerre.football-logos.cc.svg`,
    660: `${COMMUNITY_PACK_CDN}/Ligue%202/france_ligue-2.football-logos.cc.svg`,
    661: `${COMMUNITY_PACK_CDN}/Ligue%202/france_angers.football-logos.cc.svg`,
    662: `${COMMUNITY_PACK_CDN}/Ligue%202/france_ligue-2.football-logos.cc.svg`,
    663: `${COMMUNITY_PACK_CDN}/Ligue%202/france_ligue-2.football-logos.cc.svg`,
    664: `${COMMUNITY_PACK_CDN}/Ligue%202/france_ligue-2.football-logos.cc.svg`,
    665: `${COMMUNITY_PACK_CDN}/Ligue%202/france_ligue-2.football-logos.cc.svg`,
    666: `${COMMUNITY_PACK_CDN}/Ligue%202/france_ligue-2.football-logos.cc.svg`,
    667: `${COMMUNITY_PACK_CDN}/Ligue%202/france_ligue-2.football-logos.cc.svg`,
    668: `${COMMUNITY_PACK_CDN}/Ligue%202/france_ligue-2.football-logos.cc.svg`,
};

export const ARG_CLUB_LOGOS_BY_NAME: Record<string, string> = {
    // Argentina - Primera División
    'boca juniors': ARG_CLUB_LOGOS_BY_ID[701],
    'river plate': ARG_CLUB_LOGOS_BY_ID[702],
    'racing club': ARG_CLUB_LOGOS_BY_ID[703],
    'independiente': ARG_CLUB_LOGOS_BY_ID[704],
    'san lorenzo': ARG_CLUB_LOGOS_BY_ID[705],
    'san lorenzo de almagro': ARG_CLUB_LOGOS_BY_ID[705],
    'estudiantes': ARG_CLUB_LOGOS_BY_ID[706],
    'estudiantes de la plata': ARG_CLUB_LOGOS_BY_ID[706],
    'estudiantes lp': ARG_CLUB_LOGOS_BY_ID[706],
    'velez sarsfield': ARG_CLUB_LOGOS_BY_ID[707],
    'velez': ARG_CLUB_LOGOS_BY_ID[707],
    'huracan': ARG_CLUB_LOGOS_BY_ID[708],
    'ca huracan': ARG_CLUB_LOGOS_BY_ID[708],
    'rosario central': ARG_CLUB_LOGOS_BY_ID[709],
    'newells old boys': ARG_CLUB_LOGOS_BY_ID[710],
    'newells': ARG_CLUB_LOGOS_BY_ID[710],
    'talleres': ARG_CLUB_LOGOS_BY_ID[711],
    'talleres cordoba': ARG_CLUB_LOGOS_BY_ID[711],
    'talleres de cordoba': ARG_CLUB_LOGOS_BY_ID[711],
    'atletico tucuman': ARG_CLUB_LOGOS_BY_ID[712],
    'defensa y justicia': ARG_CLUB_LOGOS_BY_ID[714],
    'lanus': ARG_CLUB_LOGOS_BY_ID[715],
    'belgrano': ARG_CLUB_LOGOS_BY_ID[716],
    'instituto': ARG_CLUB_LOGOS_BY_ID[717],
    'instituto cordoba': ARG_CLUB_LOGOS_BY_ID[717],
    'sarmiento': ARG_CLUB_LOGOS_BY_ID[718],
    'sarmiento de junin': ARG_CLUB_LOGOS_BY_ID[718],
    'central cordoba': ARG_CLUB_LOGOS_BY_ID[719],
    'central cordoba sde': ARG_CLUB_LOGOS_BY_ID[719],
    'barracas central': ARG_CLUB_LOGOS_BY_ID[720],
    'platense': ARG_CLUB_LOGOS_BY_ID[722],
    'tigre': ARG_CLUB_LOGOS_BY_ID[723],
    'union': ARG_CLUB_LOGOS_BY_ID[724],
    'union de santa fe': ARG_CLUB_LOGOS_BY_ID[724],
    'argentinos juniors': ARG_CLUB_LOGOS_BY_ID[726],
    'deportivo riestra': ARG_CLUB_LOGOS_BY_ID[727],
    'riestra': ARG_CLUB_LOGOS_BY_ID[727],
    'gimnasia mendoza': ARG_CLUB_LOGOS_BY_ID[728],
    'gimnasia y esgrima mendoza': ARG_CLUB_LOGOS_BY_ID[728],
    'gimnasia lp': ARG_CLUB_LOGOS_BY_ID[729],
    'gimnasia la plata': ARG_CLUB_LOGOS_BY_ID[729],
    'banfield': ARG_CLUB_LOGOS_BY_ID[730],
    'independiente rivadavia': ARG_CLUB_LOGOS_BY_ID[731],
    'aldosivi': ARG_CLUB_LOGOS_BY_ID[732],
    'estudiantes rio cuarto': ARG_CLUB_LOGOS_BY_ID[733],

    // Argentina - Primera Nacional
    'chaco for ever': ARG_CLUB_LOGOS_BY_ID[753],
    'nueva chicago': ARG_CLUB_LOGOS_BY_ID[754],
    'almagro': ARG_CLUB_LOGOS_BY_ID[755],
    'all boys': ARG_CLUB_LOGOS_BY_ID[756],
    'estudiantes ba': ARG_CLUB_LOGOS_BY_ID[757],
    'estudiantes de buenos aires': ARG_CLUB_LOGOS_BY_ID[757],
    'deportivo moron': ARG_CLUB_LOGOS_BY_ID[759],
    'moron': ARG_CLUB_LOGOS_BY_ID[759],
    'ferro carril oeste': ARG_CLUB_LOGOS_BY_ID[760],
    'ferro': ARG_CLUB_LOGOS_BY_ID[760],
    'agropecuario': ARG_CLUB_LOGOS_BY_ID[761],
    'almirante brown': ARG_CLUB_LOGOS_BY_ID[762],
    'chacarita juniors': ARG_CLUB_LOGOS_BY_ID[764],
    'chacarita': ARG_CLUB_LOGOS_BY_ID[764],
    'temperley': ARG_CLUB_LOGOS_BY_ID[765],
    'mitre': ARG_CLUB_LOGOS_BY_ID[766],
    'mitre sde': ARG_CLUB_LOGOS_BY_ID[766],
    'colon': ARG_CLUB_LOGOS_BY_ID[767],
    'colon de santa fe': ARG_CLUB_LOGOS_BY_ID[767],
    'quilmes': ARG_CLUB_LOGOS_BY_ID[770],
    'central norte': ARG_CLUB_LOGOS_BY_ID[771],
    'defensores de belgrano': ARG_CLUB_LOGOS_BY_ID[773],
    'deportivo madryn': ARG_CLUB_LOGOS_BY_ID[774],
    'los andes': ARG_CLUB_LOGOS_BY_ID[775],
    'racing de cordoba': ARG_CLUB_LOGOS_BY_ID[776],
    'san miguel': ARG_CLUB_LOGOS_BY_ID[777],
    'san telmo': ARG_CLUB_LOGOS_BY_ID[778],
    'atlanta': ARG_CLUB_LOGOS_BY_ID[779],
    'colegiales': ARG_CLUB_LOGOS_BY_ID[781],
    'deportivo maipu': ARG_CLUB_LOGOS_BY_ID[782],
    'gimnasia jujuy': ARG_CLUB_LOGOS_BY_ID[784],
    'gimnasia y tiro': ARG_CLUB_LOGOS_BY_ID[785],
    'guemes': ARG_CLUB_LOGOS_BY_ID[786],
    'patronato': ARG_CLUB_LOGOS_BY_ID[787],
    'san martin de tucuman': ARG_CLUB_LOGOS_BY_ID[788],
    'san martin tucuman': ARG_CLUB_LOGOS_BY_ID[788],
    'tristan suarez': ARG_CLUB_LOGOS_BY_ID[789],

    // England - Premier League
    'arsenal': ARG_CLUB_LOGOS_BY_ID[1],
    'aston villa': ARG_CLUB_LOGOS_BY_ID[2],
    'chelsea': ARG_CLUB_LOGOS_BY_ID[3],
    'liverpool': ARG_CLUB_LOGOS_BY_ID[4],
    'manchester city': ARG_CLUB_LOGOS_BY_ID[5],
    'man city': ARG_CLUB_LOGOS_BY_ID[5],
    'manchester utd': ARG_CLUB_LOGOS_BY_ID[6],
    'manchester united': ARG_CLUB_LOGOS_BY_ID[6],
    'man utd': ARG_CLUB_LOGOS_BY_ID[6],
    'newcastle utd': ARG_CLUB_LOGOS_BY_ID[7],
    'newcastle united': ARG_CLUB_LOGOS_BY_ID[7],
    'newcastle': ARG_CLUB_LOGOS_BY_ID[7],
    'tottenham': ARG_CLUB_LOGOS_BY_ID[8],
    'tottenham hotspur': ARG_CLUB_LOGOS_BY_ID[8],
    'spurs': ARG_CLUB_LOGOS_BY_ID[8],
    'west ham': ARG_CLUB_LOGOS_BY_ID[9],
    'west ham united': ARG_CLUB_LOGOS_BY_ID[9],
    'brighton': ARG_CLUB_LOGOS_BY_ID[10],
    'brighton and hove albion': ARG_CLUB_LOGOS_BY_ID[10],
    'brighton & hove albion': ARG_CLUB_LOGOS_BY_ID[10],
    'fulham': ARG_CLUB_LOGOS_BY_ID[11],
    'crystal palace': ARG_CLUB_LOGOS_BY_ID[12],
    'brentford': ARG_CLUB_LOGOS_BY_ID[13],
    'everton': ARG_CLUB_LOGOS_BY_ID[14],
    'nottm forest': ARG_CLUB_LOGOS_BY_ID[15],
    'nottingham forest': ARG_CLUB_LOGOS_BY_ID[15],
    'bournemouth': ARG_CLUB_LOGOS_BY_ID[16],
    'afc bournemouth': ARG_CLUB_LOGOS_BY_ID[16],
    'wolves': ARG_CLUB_LOGOS_BY_ID[17],
    'wolverhampton': ARG_CLUB_LOGOS_BY_ID[17],
    'wolverhampton wanderers': ARG_CLUB_LOGOS_BY_ID[17],
    'ipswich town': ARG_CLUB_LOGOS_BY_ID[18],
    'ipswich': ARG_CLUB_LOGOS_BY_ID[18],
    'leicester city': ARG_CLUB_LOGOS_BY_ID[19],
    'leicester': ARG_CLUB_LOGOS_BY_ID[19],
    'southampton': ARG_CLUB_LOGOS_BY_ID[20],

    // England - Championship
    'leeds united': ARG_CLUB_LOGOS_BY_ID[101],
    'leeds': ARG_CLUB_LOGOS_BY_ID[101],
    'burnley': ARG_CLUB_LOGOS_BY_ID[102],
    'luton town': ARG_CLUB_LOGOS_BY_ID[103],
    'luton': ARG_CLUB_LOGOS_BY_ID[103],
    'sheffield utd': ARG_CLUB_LOGOS_BY_ID[104],
    'sheffield united': ARG_CLUB_LOGOS_BY_ID[104],
    'west brom': ARG_CLUB_LOGOS_BY_ID[105],
    'west bromwich albion': ARG_CLUB_LOGOS_BY_ID[105],
    'norwich city': ARG_CLUB_LOGOS_BY_ID[106],
    'norwich': ARG_CLUB_LOGOS_BY_ID[106],
    'hull city': ARG_CLUB_LOGOS_BY_ID[107],
    'hull': ARG_CLUB_LOGOS_BY_ID[107],
    'coventry city': ARG_CLUB_LOGOS_BY_ID[108],
    'coventry': ARG_CLUB_LOGOS_BY_ID[108],
    'middlesbrough': ARG_CLUB_LOGOS_BY_ID[109],
    'preston': ARG_CLUB_LOGOS_BY_ID[110],
    'preston north end': ARG_CLUB_LOGOS_BY_ID[110],
    'cardiff city': ARG_CLUB_LOGOS_BY_ID[111],
    'cardiff': ARG_CLUB_LOGOS_BY_ID[111],
    'bristol city': ARG_CLUB_LOGOS_BY_ID[112],
    'sunderland': ARG_CLUB_LOGOS_BY_ID[113],
    'swansea city': ARG_CLUB_LOGOS_BY_ID[114],
    'swansea': ARG_CLUB_LOGOS_BY_ID[114],
    'watford': ARG_CLUB_LOGOS_BY_ID[115],
    'millwall': ARG_CLUB_LOGOS_BY_ID[116],
    'qpr': ARG_CLUB_LOGOS_BY_ID[117],
    'queens park rangers': ARG_CLUB_LOGOS_BY_ID[117],
    'stoke city': ARG_CLUB_LOGOS_BY_ID[118],
    'stoke': ARG_CLUB_LOGOS_BY_ID[118],
    'blackburn': ARG_CLUB_LOGOS_BY_ID[119],
    'blackburn rovers': ARG_CLUB_LOGOS_BY_ID[119],
    'sheffield wed': ARG_CLUB_LOGOS_BY_ID[120],
    'sheffield wednesday': ARG_CLUB_LOGOS_BY_ID[120],
    'plymouth': ARG_CLUB_LOGOS_BY_ID[121],
    'plymouth argyle': ARG_CLUB_LOGOS_BY_ID[121],
    'portsmouth': ARG_CLUB_LOGOS_BY_ID[122],
    'derby county': ARG_CLUB_LOGOS_BY_ID[123],
    'derby': ARG_CLUB_LOGOS_BY_ID[123],
    'oxford united': ARG_CLUB_LOGOS_BY_ID[124],
    'oxford': ARG_CLUB_LOGOS_BY_ID[124],

    // Italy - Serie A
    'inter milano': ARG_CLUB_LOGOS_BY_ID[501],
    'inter': ARG_CLUB_LOGOS_BY_ID[501],
    'ac milan': ARG_CLUB_LOGOS_BY_ID[502],
    'milan': ARG_CLUB_LOGOS_BY_ID[502],
    'juventus': ARG_CLUB_LOGOS_BY_ID[503],
    'as roma': ARG_CLUB_LOGOS_BY_ID[504],
    'roma': ARG_CLUB_LOGOS_BY_ID[504],
    'ssc napoli': ARG_CLUB_LOGOS_BY_ID[505],
    'napoli': ARG_CLUB_LOGOS_BY_ID[505],
    'atalanta': ARG_CLUB_LOGOS_BY_ID[506],
    'lazio': ARG_CLUB_LOGOS_BY_ID[507],
    'fiorentina': ARG_CLUB_LOGOS_BY_ID[508],
    'torino': ARG_CLUB_LOGOS_BY_ID[509],
    'bologna': ARG_CLUB_LOGOS_BY_ID[510],
    'genoa': ARG_CLUB_LOGOS_BY_ID[511],
    'monza': ARG_CLUB_LOGOS_BY_ID[512],
    'lecce': ARG_CLUB_LOGOS_BY_ID[513],
    'udinese': ARG_CLUB_LOGOS_BY_ID[514],
    'hellas verona': ARG_CLUB_LOGOS_BY_ID[515],
    'verona': ARG_CLUB_LOGOS_BY_ID[515],
    'empoli': ARG_CLUB_LOGOS_BY_ID[516],
    'cagliari': ARG_CLUB_LOGOS_BY_ID[517],
    'como': ARG_CLUB_LOGOS_BY_ID[518],
    'parma': ARG_CLUB_LOGOS_BY_ID[519],
    'venezia': ARG_CLUB_LOGOS_BY_ID[520],
    'sassuolo': `${COMMUNITY_PACK_CDN}/Serie%20A/italy_sassuolo.football-logos.cc.svg`,

    // Italy - Serie B
    'palermo': ARG_CLUB_LOGOS_BY_ID[963],
    'catanzaro': ARG_CLUB_LOGOS_BY_ID[965],
    'cremonese': ARG_CLUB_LOGOS_BY_ID[967],
    'modena': ARG_CLUB_LOGOS_BY_ID[968],
    'modena fc': ARG_CLUB_LOGOS_BY_ID[968],
    'cesena': ARG_CLUB_LOGOS_BY_ID[969],
    'pisa': ARG_CLUB_LOGOS_BY_ID[971],
    'pisa sc': ARG_CLUB_LOGOS_BY_ID[971],
    'sudtirol': ARG_CLUB_LOGOS_BY_ID[973],
    'südtirol': ARG_CLUB_LOGOS_BY_ID[973],
    'mantova': ARG_CLUB_LOGOS_BY_ID[974],
    'carrarese': ARG_CLUB_LOGOS_BY_ID[975],
    'juve stabia': ARG_CLUB_LOGOS_BY_ID[977],
    'frosinone': ARG_CLUB_LOGOS_BY_ID[978],
    'sampdoria': `${COMMUNITY_PACK_CDN}/Serie%20B/italy_sampdoria.football-logos.cc.svg`,
    'arezzo': `${COMMUNITY_PACK_CDN}/Serie%20B/italy_arezzo.football-logos.cc.svg`,
    'ascoli': `${COMMUNITY_PACK_CDN}/Serie%20B/italy_ascoli.football-logos.cc.svg`,
    'benevento': `${COMMUNITY_PACK_CDN}/Serie%20B/italy_benevento.football-logos.cc.svg`,
    'padova': `${COMMUNITY_PACK_CDN}/Serie%20B/italy_padova.football-logos.cc.svg`,
    'avellino': `${COMMUNITY_PACK_CDN}/Serie%20B/italy_us-avellino-1912.football-logos.cc.svg`,
    'vicenza': `${COMMUNITY_PACK_CDN}/Serie%20B/italy_vicenza.football-logos.cc.svg`,
    'virtus entella': `${COMMUNITY_PACK_CDN}/Serie%20B/italy_virtus-entella.football-logos.cc.svg`,

    // Brazil - Serie A & Serie B
    'flamengo': ARG_CLUB_LOGOS_BY_ID[801],
    'cr flamengo': ARG_CLUB_LOGOS_BY_ID[801],
    'palmeiras': ARG_CLUB_LOGOS_BY_ID[802],
    'se palmeiras': ARG_CLUB_LOGOS_BY_ID[802],
    'sao paulo': ARG_CLUB_LOGOS_BY_ID[803],
    'são paulo': ARG_CLUB_LOGOS_BY_ID[803],
    'sao paulo fc': ARG_CLUB_LOGOS_BY_ID[803],
    'são paulo fc': ARG_CLUB_LOGOS_BY_ID[803],
    'corinthians': ARG_CLUB_LOGOS_BY_ID[804],
    'sc corinthians': ARG_CLUB_LOGOS_BY_ID[804],
    'santos': ARG_CLUB_LOGOS_BY_ID[805],
    'santos fc': ARG_CLUB_LOGOS_BY_ID[805],
    'gremio': ARG_CLUB_LOGOS_BY_ID[806],
    'grêmio': ARG_CLUB_LOGOS_BY_ID[806],
    'gremio fbpa': ARG_CLUB_LOGOS_BY_ID[806],
    'internacional': ARG_CLUB_LOGOS_BY_ID[807],
    'sc internacional': ARG_CLUB_LOGOS_BY_ID[807],
    'inter rs': ARG_CLUB_LOGOS_BY_ID[807],
    'atletico mineiro': ARG_CLUB_LOGOS_BY_ID[808],
    'atlético mineiro': ARG_CLUB_LOGOS_BY_ID[808],
    'atletico mg': ARG_CLUB_LOGOS_BY_ID[808],
    'atlético mg': ARG_CLUB_LOGOS_BY_ID[808],
    'fluminense': ARG_CLUB_LOGOS_BY_ID[809],
    'fluminense fc': ARG_CLUB_LOGOS_BY_ID[809],
    'botafogo': ARG_CLUB_LOGOS_BY_ID[810],
    'botafogo fr': ARG_CLUB_LOGOS_BY_ID[810],
    'vasco da gama': ARG_CLUB_LOGOS_BY_ID[811],
    'vasco': ARG_CLUB_LOGOS_BY_ID[811],
    'cr vasco da gama': ARG_CLUB_LOGOS_BY_ID[811],
    'cruzeiro': ARG_CLUB_LOGOS_BY_ID[812],
    'cruzeiro ec': ARG_CLUB_LOGOS_BY_ID[812],
    'bahia': ARG_CLUB_LOGOS_BY_ID[813],
    'ec bahia': ARG_CLUB_LOGOS_BY_ID[813],
    'fortaleza': ARG_CLUB_LOGOS_BY_ID[814],
    'fortaleza ec': ARG_CLUB_LOGOS_BY_ID[814],
    'ceara': ARG_CLUB_LOGOS_BY_ID[815],
    'ceará': ARG_CLUB_LOGOS_BY_ID[815],
    'ceara sc': ARG_CLUB_LOGOS_BY_ID[815],
    'ceará sc': ARG_CLUB_LOGOS_BY_ID[815],
    'athletico paranaense': ARG_CLUB_LOGOS_BY_ID[816],
    'athletico pr': ARG_CLUB_LOGOS_BY_ID[816],
    'atletico paranaense': ARG_CLUB_LOGOS_BY_ID[816],
    'coritiba': ARG_CLUB_LOGOS_BY_ID[817],
    'coritiba fbc': ARG_CLUB_LOGOS_BY_ID[817],
    'bragantino': ARG_CLUB_LOGOS_BY_ID[818],
    'red bull bragantino': ARG_CLUB_LOGOS_BY_ID[818],
    'rb bragantino': ARG_CLUB_LOGOS_BY_ID[818],
    'america mineiro': ARG_CLUB_LOGOS_BY_ID[819],
    'américa mineiro': ARG_CLUB_LOGOS_BY_ID[819],
    'america mg': ARG_CLUB_LOGOS_BY_ID[819],
    'américa mg': ARG_CLUB_LOGOS_BY_ID[819],
    'cuiaba': ARG_CLUB_LOGOS_BY_ID[820],
    'cuiabá': ARG_CLUB_LOGOS_BY_ID[820],
    'cuiaba ec': ARG_CLUB_LOGOS_BY_ID[820],
    'goias': ARG_CLUB_LOGOS_BY_ID[851],
    'goiás': ARG_CLUB_LOGOS_BY_ID[851],
    'goias ec': ARG_CLUB_LOGOS_BY_ID[851],
    'sport recife': ARG_CLUB_LOGOS_BY_ID[852],
    'sport': ARG_CLUB_LOGOS_BY_ID[852],
    'sport club do recife': ARG_CLUB_LOGOS_BY_ID[852],
    'ponte preta': ARG_CLUB_LOGOS_BY_ID[853],
    'aa ponte preta': ARG_CLUB_LOGOS_BY_ID[853],
    'crb': ARG_CLUB_LOGOS_BY_ID[856],
    'novorizontino': ARG_CLUB_LOGOS_BY_ID[857],
    'gremio novorizontino': ARG_CLUB_LOGOS_BY_ID[857],
    'operario': ARG_CLUB_LOGOS_BY_ID[858],
    'operário': ARG_CLUB_LOGOS_BY_ID[858],
    'operario ferroviario': ARG_CLUB_LOGOS_BY_ID[858],
    'operário ferroviário': ARG_CLUB_LOGOS_BY_ID[858],
    'botafogo sp': ARG_CLUB_LOGOS_BY_ID[860],
    'botafogo sp ribeirao': ARG_CLUB_LOGOS_BY_ID[860],
    'londrina': ARG_CLUB_LOGOS_BY_ID[861],
    'londrina ec': ARG_CLUB_LOGOS_BY_ID[861],
    'chapecoense': ARG_CLUB_LOGOS_BY_ID[862],
    'mirassol': ARG_CLUB_LOGOS_BY_ID[865],
    'mirassol fc': ARG_CLUB_LOGOS_BY_ID[865],
    'atletico goianiense': ARG_CLUB_LOGOS_BY_ID[867],
    'atlético goianiense': ARG_CLUB_LOGOS_BY_ID[867],
    'atletico go': ARG_CLUB_LOGOS_BY_ID[867],
    'atlético go': ARG_CLUB_LOGOS_BY_ID[867],
    'juventude': ARG_CLUB_LOGOS_BY_ID[868],
    'ec juventude': ARG_CLUB_LOGOS_BY_ID[868],
    'vitoria': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_vitoria.football-logos.cc.svg`,
    'vitória': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_vitoria.football-logos.cc.svg`,
    'ec vitoria': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_vitoria.football-logos.cc.svg`,
    'remo': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_clube-do-remo.football-logos.cc.svg`,
    'clube do remo': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20A/brazil_clube-do-remo.football-logos.cc.svg`,
    'athletic club mg': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_athletic.football-logos.cc.svg`,
    'athletic mg': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_athletic.football-logos.cc.svg`,
    'avai': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_avai.football-logos.cc.svg`,
    'avaí': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_avai.football-logos.cc.svg`,
    'criciuma': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_criciuma.football-logos.cc.svg`,
    'criciúma': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_criciuma.football-logos.cc.svg`,
    'nautico': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_nautico.football-logos.cc.svg`,
    'náutico': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_nautico.football-logos.cc.svg`,
    'sao bernardo': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_sao-bernardo.football-logos.cc.svg`,
    'são bernardo': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_sao-bernardo.football-logos.cc.svg`,
    'vila nova': `${COMMUNITY_PACK_CDN}/Brazilian%20Serie%20B/brazil_vila-nova.football-logos.cc.svg`,

    // Spain - La Liga & Segunda División (La Liga 2)
    'real madrid': ARG_CLUB_LOGOS_BY_ID[201],
    'real madrid cf': ARG_CLUB_LOGOS_BY_ID[201],
    'fc barcelona': ARG_CLUB_LOGOS_BY_ID[202],
    'barcelona': ARG_CLUB_LOGOS_BY_ID[202],
    'barca': ARG_CLUB_LOGOS_BY_ID[202],
    'barça': ARG_CLUB_LOGOS_BY_ID[202],
    'atletico madrid': ARG_CLUB_LOGOS_BY_ID[203],
    'atlético madrid': ARG_CLUB_LOGOS_BY_ID[203],
    'atletico de madrid': ARG_CLUB_LOGOS_BY_ID[203],
    'atlético de madrid': ARG_CLUB_LOGOS_BY_ID[203],
    'atleti': ARG_CLUB_LOGOS_BY_ID[203],
    'athletic club': ARG_CLUB_LOGOS_BY_ID[204],
    'athletic bilbao': ARG_CLUB_LOGOS_BY_ID[204],
    'athletic': ARG_CLUB_LOGOS_BY_ID[204],
    'real sociedad': ARG_CLUB_LOGOS_BY_ID[205],
    'la real': ARG_CLUB_LOGOS_BY_ID[205],
    'real betis': ARG_CLUB_LOGOS_BY_ID[206],
    'betis': ARG_CLUB_LOGOS_BY_ID[206],
    'girona': ARG_CLUB_LOGOS_BY_ID[207],
    'girona fc': ARG_CLUB_LOGOS_BY_ID[207],
    'villarreal': ARG_CLUB_LOGOS_BY_ID[208],
    'villarreal cf': ARG_CLUB_LOGOS_BY_ID[208],
    'valencia': ARG_CLUB_LOGOS_BY_ID[209],
    'valencia cf': ARG_CLUB_LOGOS_BY_ID[209],
    'sevilla': ARG_CLUB_LOGOS_BY_ID[210],
    'sevilla fc': ARG_CLUB_LOGOS_BY_ID[210],
    'celta vigo': ARG_CLUB_LOGOS_BY_ID[211],
    'celta de vigo': ARG_CLUB_LOGOS_BY_ID[211],
    'celta': ARG_CLUB_LOGOS_BY_ID[211],
    'rc celta': ARG_CLUB_LOGOS_BY_ID[211],
    'osasuna': ARG_CLUB_LOGOS_BY_ID[212],
    'ca osasuna': ARG_CLUB_LOGOS_BY_ID[212],
    'getafe': ARG_CLUB_LOGOS_BY_ID[213],
    'getafe cf': ARG_CLUB_LOGOS_BY_ID[213],
    'mallorca': ARG_CLUB_LOGOS_BY_ID[214],
    'rcd mallorca': ARG_CLUB_LOGOS_BY_ID[214],
    'rayo vallecano': ARG_CLUB_LOGOS_BY_ID[215],
    'rayo': ARG_CLUB_LOGOS_BY_ID[215],
    'las palmas': ARG_CLUB_LOGOS_BY_ID[216],
    'ud las palmas': ARG_CLUB_LOGOS_BY_ID[216],
    'alaves': ARG_CLUB_LOGOS_BY_ID[217],
    'alavés': ARG_CLUB_LOGOS_BY_ID[217],
    'deportivo alaves': ARG_CLUB_LOGOS_BY_ID[217],
    'deportivo alavés': ARG_CLUB_LOGOS_BY_ID[217],
    'leganes': ARG_CLUB_LOGOS_BY_ID[218],
    'leganés': ARG_CLUB_LOGOS_BY_ID[218],
    'cd leganes': ARG_CLUB_LOGOS_BY_ID[218],
    'cd leganés': ARG_CLUB_LOGOS_BY_ID[218],
    'valladolid': ARG_CLUB_LOGOS_BY_ID[219],
    'real valladolid': ARG_CLUB_LOGOS_BY_ID[219],
    'espanyol': ARG_CLUB_LOGOS_BY_ID[220],
    'rcd espanyol': ARG_CLUB_LOGOS_BY_ID[220],
    'elche': ARG_CLUB_LOGOS_BY_ID[901],
    'elche cf': ARG_CLUB_LOGOS_BY_ID[901],
    'sporting gijon': ARG_CLUB_LOGOS_BY_ID[902],
    'sporting gijón': ARG_CLUB_LOGOS_BY_ID[902],
    'sporting de gijon': ARG_CLUB_LOGOS_BY_ID[902],
    'malaga': ARG_CLUB_LOGOS_BY_ID[903],
    'málaga': ARG_CLUB_LOGOS_BY_ID[903],
    'malaga cf': ARG_CLUB_LOGOS_BY_ID[903],
    'málaga cf': ARG_CLUB_LOGOS_BY_ID[903],
    'zaragoza': ARG_CLUB_LOGOS_BY_ID[904],
    'real zaragoza': ARG_CLUB_LOGOS_BY_ID[904],
    'tenerife': ARG_CLUB_LOGOS_BY_ID[905],
    'cd tenerife': ARG_CLUB_LOGOS_BY_ID[905],
    'cartagena': ARG_CLUB_LOGOS_BY_ID[906],
    'fc cartagena': ARG_CLUB_LOGOS_BY_ID[906],
    'racing santander': ARG_CLUB_LOGOS_BY_ID[907],
    'racing de santander': ARG_CLUB_LOGOS_BY_ID[907],
    'racing': ARG_CLUB_LOGOS_BY_ID[907],
    'andorra': ARG_CLUB_LOGOS_BY_ID[908],
    'fc andorra': ARG_CLUB_LOGOS_BY_ID[908],
    'villarreal b': ARG_CLUB_LOGOS_BY_ID[909],
    'espanyol b': ARG_CLUB_LOGOS_BY_ID[910],
    'almeria': ARG_CLUB_LOGOS_BY_ID[911],
    'almería': ARG_CLUB_LOGOS_BY_ID[911],
    'ud almeria': ARG_CLUB_LOGOS_BY_ID[911],
    'ud almería': ARG_CLUB_LOGOS_BY_ID[911],
    'mirandes': ARG_CLUB_LOGOS_BY_ID[912],
    'mirandés': ARG_CLUB_LOGOS_BY_ID[912],
    'cd mirandes': ARG_CLUB_LOGOS_BY_ID[912],
    'burgos': ARG_CLUB_LOGOS_BY_ID[913],
    'burgos cf': ARG_CLUB_LOGOS_BY_ID[913],
    'ferrol': ARG_CLUB_LOGOS_BY_ID[914],
    'racing ferrol': ARG_CLUB_LOGOS_BY_ID[914],
    'racing club ferrol': ARG_CLUB_LOGOS_BY_ID[914],
    'eldense': ARG_CLUB_LOGOS_BY_ID[915],
    'cd eldense': ARG_CLUB_LOGOS_BY_ID[915],
    'levante': ARG_CLUB_LOGOS_BY_ID[916],
    'levante ud': ARG_CLUB_LOGOS_BY_ID[916],
    'castellon': ARG_CLUB_LOGOS_BY_ID[917],
    'castellón': ARG_CLUB_LOGOS_BY_ID[917],
    'cd castellon': ARG_CLUB_LOGOS_BY_ID[917],
    'cordoba': ARG_CLUB_LOGOS_BY_ID[918],
    'córdoba': ARG_CLUB_LOGOS_BY_ID[918],
    'cordoba cf': ARG_CLUB_LOGOS_BY_ID[918],
    'córdoba cf': ARG_CLUB_LOGOS_BY_ID[918],
    'oviedo': ARG_CLUB_LOGOS_BY_ID[919],
    'real oviedo': ARG_CLUB_LOGOS_BY_ID[919],
    'huesca': ARG_CLUB_LOGOS_BY_ID[920],
    'sd huesca': ARG_CLUB_LOGOS_BY_ID[920],
    'eibar': ARG_CLUB_LOGOS_BY_ID[921],
    'sd eibar': ARG_CLUB_LOGOS_BY_ID[921],
    'deportivo la coruna': `${COMMUNITY_PACK_CDN}/La%20Liga/spain_deportivo-la-coruna.football-logos.cc.svg`,
    'deportivo la coruña': `${COMMUNITY_PACK_CDN}/La%20Liga/spain_deportivo-la-coruna.football-logos.cc.svg`,
    'deportivo': `${COMMUNITY_PACK_CDN}/La%20Liga/spain_deportivo.football-logos.cc.svg`,
    'rc deportivo': `${COMMUNITY_PACK_CDN}/La%20Liga/spain_deportivo-la-coruna.football-logos.cc.svg`,

    // ==========================================
    // Alemania - Bundesliga y 2. Bundesliga
    // ==========================================
    'bayern': ARG_CLUB_LOGOS_BY_ID[401],
    'bayern munchen': ARG_CLUB_LOGOS_BY_ID[401],
    'bayern münchen': ARG_CLUB_LOGOS_BY_ID[401],
    'fc bayern': ARG_CLUB_LOGOS_BY_ID[401],
    'fc bayern munchen': ARG_CLUB_LOGOS_BY_ID[401],
    'fc bayern münchen': ARG_CLUB_LOGOS_BY_ID[401],
    'bayern munich': ARG_CLUB_LOGOS_BY_ID[401],
    'borussia dortmund': ARG_CLUB_LOGOS_BY_ID[402],
    'dortmund': ARG_CLUB_LOGOS_BY_ID[402],
    'bvb': ARG_CLUB_LOGOS_BY_ID[402],
    'bvb 09': ARG_CLUB_LOGOS_BY_ID[402],
    'bayer leverkusen': ARG_CLUB_LOGOS_BY_ID[403],
    'leverkusen': ARG_CLUB_LOGOS_BY_ID[403],
    'bayer 04': ARG_CLUB_LOGOS_BY_ID[403],
    'bayer 04 leverkusen': ARG_CLUB_LOGOS_BY_ID[403],
    'rb leipzig': ARG_CLUB_LOGOS_BY_ID[404],
    'leipzig': ARG_CLUB_LOGOS_BY_ID[404],
    'rasenballsport leipzig': ARG_CLUB_LOGOS_BY_ID[404],
    'eintracht frankfurt': ARG_CLUB_LOGOS_BY_ID[405],
    'frankfurt': ARG_CLUB_LOGOS_BY_ID[405],
    'eintracht': ARG_CLUB_LOGOS_BY_ID[405],
    'vfb stuttgart': ARG_CLUB_LOGOS_BY_ID[406],
    'stuttgart': ARG_CLUB_LOGOS_BY_ID[406],
    'sc freiburg': ARG_CLUB_LOGOS_BY_ID[407],
    'freiburg': ARG_CLUB_LOGOS_BY_ID[407],
    'tsg hoffenheim': ARG_CLUB_LOGOS_BY_ID[408],
    'hoffenheim': ARG_CLUB_LOGOS_BY_ID[408],
    'tsg 1899 hoffenheim': ARG_CLUB_LOGOS_BY_ID[408],
    'heidenheim': ARG_CLUB_LOGOS_BY_ID[409],
    '1 fc heidenheim': ARG_CLUB_LOGOS_BY_ID[409],
    '1. fc heidenheim': ARG_CLUB_LOGOS_BY_ID[409],
    'werder bremen': ARG_CLUB_LOGOS_BY_ID[410],
    'bremen': ARG_CLUB_LOGOS_BY_ID[410],
    'sv werder bremen': ARG_CLUB_LOGOS_BY_ID[410],
    'augsburg': ARG_CLUB_LOGOS_BY_ID[411],
    'fc augsburg': ARG_CLUB_LOGOS_BY_ID[411],
    'wolfsburg': ARG_CLUB_LOGOS_BY_ID[412],
    'vfl wolfsburg': ARG_CLUB_LOGOS_BY_ID[412],
    'mainz': ARG_CLUB_LOGOS_BY_ID[413],
    'mainz 05': ARG_CLUB_LOGOS_BY_ID[413],
    'fsv mainz': ARG_CLUB_LOGOS_BY_ID[413],
    'fsv mainz 05': ARG_CLUB_LOGOS_BY_ID[413],
    '1 fsv mainz 05': ARG_CLUB_LOGOS_BY_ID[413],
    'monchengladbach': ARG_CLUB_LOGOS_BY_ID[414],
    'mönchengladbach': ARG_CLUB_LOGOS_BY_ID[414],
    'bor monchengladbach': ARG_CLUB_LOGOS_BY_ID[414],
    'bor. mönchengladbach': ARG_CLUB_LOGOS_BY_ID[414],
    'borussia monchengladbach': ARG_CLUB_LOGOS_BY_ID[414],
    'borussia mönchengladbach': ARG_CLUB_LOGOS_BY_ID[414],
    'gladbach': ARG_CLUB_LOGOS_BY_ID[414],
    'bochum': ARG_CLUB_LOGOS_BY_ID[415],
    'vfl bochum': ARG_CLUB_LOGOS_BY_ID[415],
    'union berlin': ARG_CLUB_LOGOS_BY_ID[416],
    '1 fc union berlin': ARG_CLUB_LOGOS_BY_ID[416],
    '1. fc union berlin': ARG_CLUB_LOGOS_BY_ID[416],
    'st pauli': ARG_CLUB_LOGOS_BY_ID[417],
    'st. pauli': ARG_CLUB_LOGOS_BY_ID[417],
    'fc st pauli': ARG_CLUB_LOGOS_BY_ID[417],
    'fc st. pauli': ARG_CLUB_LOGOS_BY_ID[417],
    'holstein kiel': ARG_CLUB_LOGOS_BY_ID[418],
    'kiel': ARG_CLUB_LOGOS_BY_ID[418],
    'hamburger sv': ARG_CLUB_LOGOS_BY_ID[931],
    'hamburg': ARG_CLUB_LOGOS_BY_ID[931],
    'hsv': ARG_CLUB_LOGOS_BY_ID[931],
    'hannover 96': ARG_CLUB_LOGOS_BY_ID[932],
    'hannover': ARG_CLUB_LOGOS_BY_ID[932],
    'schalke 04': ARG_CLUB_LOGOS_BY_ID[933],
    'schalke': ARG_CLUB_LOGOS_BY_ID[933],
    'fc schalke 04': ARG_CLUB_LOGOS_BY_ID[933],
    'paderborn': ARG_CLUB_LOGOS_BY_ID[935],
    'sc paderborn': ARG_CLUB_LOGOS_BY_ID[935],
    'sc paderborn 07': ARG_CLUB_LOGOS_BY_ID[935],
    'kaiserslautern': ARG_CLUB_LOGOS_BY_ID[936],
    '1 fc kaiserslautern': ARG_CLUB_LOGOS_BY_ID[936],
    '1. fc kaiserslautern': ARG_CLUB_LOGOS_BY_ID[936],
    'nurnberg': ARG_CLUB_LOGOS_BY_ID[937],
    'nürnberg': ARG_CLUB_LOGOS_BY_ID[937],
    '1 fc nurnberg': ARG_CLUB_LOGOS_BY_ID[937],
    '1. fc nürnberg': ARG_CLUB_LOGOS_BY_ID[937],
    'hertha bsc': ARG_CLUB_LOGOS_BY_ID[938],
    'hertha': ARG_CLUB_LOGOS_BY_ID[938],
    'hertha berlin': ARG_CLUB_LOGOS_BY_ID[938],
    'greuther furth': ARG_CLUB_LOGOS_BY_ID[939],
    'greuther fürth': ARG_CLUB_LOGOS_BY_ID[939],
    'spvgg greuther furth': ARG_CLUB_LOGOS_BY_ID[939],
    'spvgg greuther fürth': ARG_CLUB_LOGOS_BY_ID[939],
    'eintracht braunschweig': ARG_CLUB_LOGOS_BY_ID[940],
    'braunschweig': ARG_CLUB_LOGOS_BY_ID[940],
    'darmstadt 98': ARG_CLUB_LOGOS_BY_ID[941],
    'darmstadt': ARG_CLUB_LOGOS_BY_ID[941],
    'sv darmstadt 98': ARG_CLUB_LOGOS_BY_ID[941],
    'koln': ARG_CLUB_LOGOS_BY_ID[942],
    'köln': ARG_CLUB_LOGOS_BY_ID[942],
    '1 fc koln': ARG_CLUB_LOGOS_BY_ID[942],
    '1. fc köln': ARG_CLUB_LOGOS_BY_ID[942],
    'karlsruher sc': ARG_CLUB_LOGOS_BY_ID[944],
    'karlsruhe': ARG_CLUB_LOGOS_BY_ID[944],
    'karlsruher': ARG_CLUB_LOGOS_BY_ID[944],
    'magdeburg': ARG_CLUB_LOGOS_BY_ID[947],
    '1 fc magdeburg': ARG_CLUB_LOGOS_BY_ID[947],
    '1. fc magdeburg': ARG_CLUB_LOGOS_BY_ID[947],
    'elversberg': ARG_CLUB_LOGOS_BY_ID[948],
    'sv elversberg': ARG_CLUB_LOGOS_BY_ID[948],
    'arminia bielefeld': `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_arminia-bielefeld.football-logos.cc.svg`,
    'bielefeld': `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_arminia-bielefeld.football-logos.cc.svg`,
    'dynamo dresden': `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_dynamo-dresden.football-logos.cc.svg`,
    'dresden': `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_dynamo-dresden.football-logos.cc.svg`,
    'energie cottbus': `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_energie-cottbus.football-logos.cc.svg`,
    'cottbus': `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_energie-cottbus.football-logos.cc.svg`,
    'osnabruck': `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_osnabruck.football-logos.cc.svg`,
    'osnabrück': `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_osnabruck.football-logos.cc.svg`,
    'vfl osnabruck': `${COMMUNITY_PACK_CDN}/Bundesliga%202/germany_osnabruck.football-logos.cc.svg`,

    // Argentina - Otros Clubes
    'godoy cruz': ARG_CLUB_LOGOS_BY_ID[721],
    'godoy cruz antonio tomba': ARG_CLUB_LOGOS_BY_ID[721],
    'club atletico platense': ARG_CLUB_LOGOS_BY_ID[722],
    'san martin de san juan': ARG_CLUB_LOGOS_BY_ID[752],
    'san martin san juan': ARG_CLUB_LOGOS_BY_ID[752],
    'san martin sj': ARG_CLUB_LOGOS_BY_ID[752],
    'guillermo brown': ARG_CLUB_LOGOS_BY_ID[772],
    'villa dalmine': ARG_CLUB_LOGOS_BY_ID[790],
    'villa dálmine': ARG_CLUB_LOGOS_BY_ID[790],
    'villa mitre': ARG_CLUB_LOGOS_BY_ID[791],
    'douglas haig': ARG_CLUB_LOGOS_BY_ID[792],
    'deportivo merlo': ARG_CLUB_LOGOS_BY_ID[793],
    'atletico policial': ARG_CLUB_LOGOS_BY_ID[794],
    'atlético policial': ARG_CLUB_LOGOS_BY_ID[794],
    'libertad sunchales': ARG_CLUB_LOGOS_BY_ID[795],
    'racing de olavarria': ARG_CLUB_LOGOS_BY_ID[796],
    'racing de olavarría': ARG_CLUB_LOGOS_BY_ID[796],
    'sportivo desamparados': ARG_CLUB_LOGOS_BY_ID[797],

    // Francia - Ligue 1
    'psg': ARG_CLUB_LOGOS_BY_ID[601],
    'paris saint germain': ARG_CLUB_LOGOS_BY_ID[601],
    'paris saint-germain': ARG_CLUB_LOGOS_BY_ID[601],
    'paris sg': ARG_CLUB_LOGOS_BY_ID[601],
    'marseille': ARG_CLUB_LOGOS_BY_ID[602],
    'olympique de marseille': ARG_CLUB_LOGOS_BY_ID[602],
    'olympique marseille': ARG_CLUB_LOGOS_BY_ID[602],
    'om': ARG_CLUB_LOGOS_BY_ID[602],
    'as monaco': ARG_CLUB_LOGOS_BY_ID[603],
    'monaco': ARG_CLUB_LOGOS_BY_ID[603],
    'stade rennais': ARG_CLUB_LOGOS_BY_ID[604],
    'rennes': ARG_CLUB_LOGOS_BY_ID[604],
    'lille': ARG_CLUB_LOGOS_BY_ID[605],
    'losc lille': ARG_CLUB_LOGOS_BY_ID[605],
    'losc': ARG_CLUB_LOGOS_BY_ID[605],
    'nice': ARG_CLUB_LOGOS_BY_ID[606],
    'ogc nice': ARG_CLUB_LOGOS_BY_ID[606],
    'lyon': ARG_CLUB_LOGOS_BY_ID[607],
    'olympique lyonnais': ARG_CLUB_LOGOS_BY_ID[607],
    'olympique lyon': ARG_CLUB_LOGOS_BY_ID[607],
    'ol': ARG_CLUB_LOGOS_BY_ID[607],
    'rc lens': ARG_CLUB_LOGOS_BY_ID[608],
    'lens': ARG_CLUB_LOGOS_BY_ID[608],
    'stade brestois': ARG_CLUB_LOGOS_BY_ID[609],
    'brest': ARG_CLUB_LOGOS_BY_ID[609],
    'montpellier': ARG_CLUB_LOGOS_BY_ID[610],
    'montpellier hsc': ARG_CLUB_LOGOS_BY_ID[610],
    'toulouse': ARG_CLUB_LOGOS_BY_ID[611],
    'toulouse fc': ARG_CLUB_LOGOS_BY_ID[611],
    'nantes': ARG_CLUB_LOGOS_BY_ID[612],
    'fc nantes': ARG_CLUB_LOGOS_BY_ID[612],
    'bordeaux': ARG_CLUB_LOGOS_BY_ID[613],
    'girondins de bordeaux': ARG_CLUB_LOGOS_BY_ID[613],
    'girondins bordeaux': ARG_CLUB_LOGOS_BY_ID[613],
    'reims': ARG_CLUB_LOGOS_BY_ID[614],
    'stade de reims': ARG_CLUB_LOGOS_BY_ID[614],
    'strasbourg': ARG_CLUB_LOGOS_BY_ID[615],
    'rc strasbourg': ARG_CLUB_LOGOS_BY_ID[615],
    'rc strasbourg alsace': ARG_CLUB_LOGOS_BY_ID[615],
    'clermont': ARG_CLUB_LOGOS_BY_ID[616],
    'clermont foot': ARG_CLUB_LOGOS_BY_ID[616],
    'metz': ARG_CLUB_LOGOS_BY_ID[617],
    'fc metz': ARG_CLUB_LOGOS_BY_ID[617],
    'le havre': ARG_CLUB_LOGOS_BY_ID[618],
    'le havre ac': ARG_CLUB_LOGOS_BY_ID[618],
    'havre ac': ARG_CLUB_LOGOS_BY_ID[618],

    // Francia - Ligue 2
    'valenciennes': ARG_CLUB_LOGOS_BY_ID[651],
    'valenciennes fc': ARG_CLUB_LOGOS_BY_ID[651],
    'caen': ARG_CLUB_LOGOS_BY_ID[652],
    'sm caen': ARG_CLUB_LOGOS_BY_ID[652],
    'grenoble': ARG_CLUB_LOGOS_BY_ID[653],
    'grenoble foot': ARG_CLUB_LOGOS_BY_ID[653],
    'paris fc': ARG_CLUB_LOGOS_BY_ID[654],
    'ajaccio': ARG_CLUB_LOGOS_BY_ID[655],
    'ac ajaccio': ARG_CLUB_LOGOS_BY_ID[655],
    'dunkerque': ARG_CLUB_LOGOS_BY_ID[656],
    'usm dunkerque': ARG_CLUB_LOGOS_BY_ID[656],
    'troyes': ARG_CLUB_LOGOS_BY_ID[657],
    'troyes ac': ARG_CLUB_LOGOS_BY_ID[657],
    'concarneau': ARG_CLUB_LOGOS_BY_ID[658],
    'us concarneau': ARG_CLUB_LOGOS_BY_ID[658],
    'auxerre': ARG_CLUB_LOGOS_BY_ID[659],
    'aj auxerre': ARG_CLUB_LOGOS_BY_ID[659],
    'amiens': ARG_CLUB_LOGOS_BY_ID[660],
    'amiens sc': ARG_CLUB_LOGOS_BY_ID[660],
    'angers': ARG_CLUB_LOGOS_BY_ID[661],
    'angers sco': ARG_CLUB_LOGOS_BY_ID[661],
    'laval': ARG_CLUB_LOGOS_BY_ID[662],
    'stade lavallois': ARG_CLUB_LOGOS_BY_ID[662],
    'rodez': ARG_CLUB_LOGOS_BY_ID[663],
    'rodez af': ARG_CLUB_LOGOS_BY_ID[663],
    'quevilly rouen': ARG_CLUB_LOGOS_BY_ID[664],
    'quevilly-rouen': ARG_CLUB_LOGOS_BY_ID[664],
    'qrm': ARG_CLUB_LOGOS_BY_ID[664],
    'red star': ARG_CLUB_LOGOS_BY_ID[665],
    'red star fc': ARG_CLUB_LOGOS_BY_ID[665],
    'bastia': ARG_CLUB_LOGOS_BY_ID[666],
    'sc bastia': ARG_CLUB_LOGOS_BY_ID[666],
    'annecy': ARG_CLUB_LOGOS_BY_ID[667],
    'fc annecy': ARG_CLUB_LOGOS_BY_ID[667],
    'guingamp': ARG_CLUB_LOGOS_BY_ID[668],
    'ea guingamp': ARG_CLUB_LOGOS_BY_ID[668],
    'le mans': `${COMMUNITY_PACK_CDN}/Ligue%202/france_le-mans.football-logos.cc.svg`,
    'lorient': `${COMMUNITY_PACK_CDN}/Ligue%202/france_lorient.football-logos.cc.svg`,
    'fc lorient': `${COMMUNITY_PACK_CDN}/Ligue%202/france_lorient.football-logos.cc.svg`,
};
