/**
 * Vector SVG badges and club logos for Argentine football
 * Source: https://github.com/Extremer12/community-data-packs (Extremer12/community-data-packs@main)
 * CDN: jsDelivr
 */

export const ARG_PACK_CDN = 'https://cdn.jsdelivr.net/gh/Extremer12/community-data-packs@main';

export const ARG_COMPETITION_LOGOS: Record<string, string> = {
    LIGA_ARGENTINA: `${ARG_PACK_CDN}/primera_division/argentina_argentina-primera-division.football-logos.cc.svg`,
    PRIMERA_NACIONAL: `${ARG_PACK_CDN}/primera_nacional/argentina_primera-nacional.football-logos.cc.svg`,
    'liga-argentina': `${ARG_PACK_CDN}/primera_division/argentina_argentina-primera-division.football-logos.cc.svg`,
    'primera-nacional': `${ARG_PACK_CDN}/primera_nacional/argentina_primera-nacional.football-logos.cc.svg`,
};

export const ARG_CLUB_LOGOS_BY_ID: Record<number | string, string> = {
    // Primera División (IDs 701-733)
    701: `${ARG_PACK_CDN}/primera_division/argentina_boca-juniors.football-logos.cc.svg`,
    702: `${ARG_PACK_CDN}/primera_division/argentina_river-plate.football-logos.cc.svg`,
    703: `${ARG_PACK_CDN}/primera_division/argentina_racing-club.football-logos.cc.svg`,
    704: `${ARG_PACK_CDN}/primera_division/argentina_independiente.football-logos.cc.svg`,
    705: `${ARG_PACK_CDN}/primera_division/argentina_san-lorenzo-de-almagro.football-logos.cc.svg`,
    706: `${ARG_PACK_CDN}/primera_division/argentina_estudiantes-de-la-plata.football-logos.cc.svg`,
    707: `${ARG_PACK_CDN}/primera_division/argentina_velez-sarsfield.football-logos.cc.svg`,
    708: `${ARG_PACK_CDN}/primera_division/argentina_ca-huracan.football-logos.cc.svg`,
    709: `${ARG_PACK_CDN}/primera_division/argentina_rosario-central.football-logos.cc.svg`,
    710: `${ARG_PACK_CDN}/primera_division/argentina_newells-old-boys.football-logos.cc.svg`,
    711: `${ARG_PACK_CDN}/primera_division/argentina_talleres.football-logos.cc.svg`,
    712: `${ARG_PACK_CDN}/primera_division/argentina_atletico-tucuman.football-logos.cc.svg`,
    714: `${ARG_PACK_CDN}/primera_division/argentina_defensa-y-justicia.football-logos.cc.svg`,
    715: `${ARG_PACK_CDN}/primera_division/argentina_lanus.football-logos.cc.svg`,
    716: `${ARG_PACK_CDN}/primera_division/argentina_belgrano.football-logos.cc.svg`,
    717: `${ARG_PACK_CDN}/primera_division/argentina_instituto-cordoba.football-logos.cc.svg`,
    718: `${ARG_PACK_CDN}/primera_division/argentina_sarmiento.football-logos.cc.svg`,
    719: `${ARG_PACK_CDN}/primera_division/argentina_central-cordoba.football-logos.cc.svg`,
    720: `${ARG_PACK_CDN}/primera_division/argentina_barracas-central.football-logos.cc.svg`,
    722: `${ARG_PACK_CDN}/primera_division/argentina_club-atletico-platanense.football-logos.cc.svg`,
    723: `${ARG_PACK_CDN}/primera_division/argentina_tigre.football-logos.cc.svg`,
    724: `${ARG_PACK_CDN}/primera_division/argentina_union.football-logos.cc.svg`,
    726: `${ARG_PACK_CDN}/primera_division/argentina_argeninos-juniors.football-logos.cc.svg`,
    727: `${ARG_PACK_CDN}/primera_division/argentina_deportivo-riestra.football-logos.cc.svg`,
    728: `${ARG_PACK_CDN}/primera_division/argentina_gimnasia-y-esgrima.football-logos.cc.svg`,
    729: `${ARG_PACK_CDN}/primera_division/argentina_gimnasia-lp.football-logos.cc.svg`,
    730: `${ARG_PACK_CDN}/primera_division/argentina_banfield.football-logos.cc.svg`,
    731: `${ARG_PACK_CDN}/primera_division/argentina_independiente-rivadavia.football-logos.cc.svg`,
    732: `${ARG_PACK_CDN}/primera_division/argentina_aldosivi.football-logos.cc.svg`,
    733: `${ARG_PACK_CDN}/primera_division/argentina_estudiantes-de-rio-cuarto.football-logos.cc.svg`,

    // Primera Nacional (IDs 750+)
    753: `${ARG_PACK_CDN}/primera_nacional/argentina_chaco-for-ever.football-logos.cc.svg`,
    754: `${ARG_PACK_CDN}/primera_nacional/argentina_nueva-chicago.football-logos.cc.svg`,
    755: `${ARG_PACK_CDN}/primera_nacional/argentina_almagro.football-logos.cc.svg`,
    756: `${ARG_PACK_CDN}/primera_nacional/argentina_all-boys.football-logos.cc.svg`,
    757: `${ARG_PACK_CDN}/primera_nacional/argentina_estudiantes-de-buenos-aires.football-logos.cc.svg`,
    759: `${ARG_PACK_CDN}/primera_nacional/argentina_deportivo-moron.football-logos.cc.svg`,
    760: `${ARG_PACK_CDN}/primera_nacional/argentina_ferro-carril-oeste.football-logos.cc.svg`,
    761: `${ARG_PACK_CDN}/primera_nacional/argentina_agropecuario-argentino.football-logos.cc.svg`,
    762: `${ARG_PACK_CDN}/primera_nacional/argentina_almirante-brown.football-logos.cc.svg`,
    764: `${ARG_PACK_CDN}/primera_nacional/argentina_chacarita-juniors.football-logos.cc.svg`,
    765: `${ARG_PACK_CDN}/primera_nacional/argentina_temperley.football-logos.cc.svg`,
    766: `${ARG_PACK_CDN}/primera_nacional/argentina_mitre-santiago-del-estero.football-logos.cc.svg`,
    767: `${ARG_PACK_CDN}/primera_nacional/argentina_colon-santa-fe.football-logos.cc.svg`,
    770: `${ARG_PACK_CDN}/primera_nacional/argentina_quilmes.football-logos.cc.svg`,
    771: `${ARG_PACK_CDN}/primera_nacional/argentina_central-norte.football-logos.cc.svg`,
    773: `${ARG_PACK_CDN}/primera_nacional/argentina_defensores-de-belgrano.football-logos.cc.svg`,
    774: `${ARG_PACK_CDN}/primera_nacional/argentina_deportivo-madryn.football-logos.cc.svg`,
    775: `${ARG_PACK_CDN}/primera_nacional/argentina_los-andes.football-logos.cc.svg`,
    776: `${ARG_PACK_CDN}/primera_nacional/argentina_racing.football-logos.cc.svg`,
    777: `${ARG_PACK_CDN}/primera_nacional/argentina_san-miguel.football-logos.cc.svg`,
    778: `${ARG_PACK_CDN}/primera_nacional/argentina_san-telmo.football-logos.cc.svg`,
    779: `${ARG_PACK_CDN}/primera_nacional/argentina_atletico-atlanta.football-logos.cc.svg`,
    781: `${ARG_PACK_CDN}/primera_nacional/argentina_colegiales.football-logos.cc.svg`,
    782: `${ARG_PACK_CDN}/primera_nacional/argentina_deportivo-maipu.football-logos.cc.svg`,
    784: `${ARG_PACK_CDN}/primera_nacional/argentina_gimnasia-de-jujuy.football-logos.cc.svg`,
    785: `${ARG_PACK_CDN}/primera_nacional/argentina_gimnasia-y-tiro.football-logos.cc.svg`,
    786: `${ARG_PACK_CDN}/primera_nacional/argentina_guemes.football-logos.cc.svg`,
    787: `${ARG_PACK_CDN}/primera_nacional/argentina_patronato.football-logos.cc.svg`,
    788: `${ARG_PACK_CDN}/primera_nacional/argentina_san-martin-tucuman.football-logos.cc.svg`,
    789: `${ARG_PACK_CDN}/primera_nacional/argentina_tristan-suarez.football-logos.cc.svg`,
};

export const ARG_CLUB_LOGOS_BY_NAME: Record<string, string> = {
    // Primera División
    'boca juniors': ARG_CLUB_LOGOS_BY_ID[701],
    'river plate': ARG_CLUB_LOGOS_BY_ID[702],
    'racing club': ARG_CLUB_LOGOS_BY_ID[703],
    'independiente': ARG_CLUB_LOGOS_BY_ID[704],
    'san lorenzo': ARG_CLUB_LOGOS_BY_ID[705],
    'san lorenzo de almagro': ARG_CLUB_LOGOS_BY_ID[705],
    'estudiantes': ARG_CLUB_LOGOS_BY_ID[706],
    'estudiantes de la plata': ARG_CLUB_LOGOS_BY_ID[706],
    'estudiantes lp': ARG_CLUB_LOGOS_BY_ID[706],
    'velez sarsfield': ARG_CLUB_LOGOS_BY_ID[707],
    'velez': ARG_CLUB_LOGOS_BY_ID[707],
    'huracan': ARG_CLUB_LOGOS_BY_ID[708],
    'ca huracan': ARG_CLUB_LOGOS_BY_ID[708],
    'rosario central': ARG_CLUB_LOGOS_BY_ID[709],
    'newells old boys': ARG_CLUB_LOGOS_BY_ID[710],
    'newells': ARG_CLUB_LOGOS_BY_ID[710],
    'talleres': ARG_CLUB_LOGOS_BY_ID[711],
    'talleres cordoba': ARG_CLUB_LOGOS_BY_ID[711],
    'talleres de cordoba': ARG_CLUB_LOGOS_BY_ID[711],
    'atletico tucuman': ARG_CLUB_LOGOS_BY_ID[712],
    'defensa y justicia': ARG_CLUB_LOGOS_BY_ID[714],
    'lanus': ARG_CLUB_LOGOS_BY_ID[715],
    'belgrano': ARG_CLUB_LOGOS_BY_ID[716],
    'instituto': ARG_CLUB_LOGOS_BY_ID[717],
    'instituto cordoba': ARG_CLUB_LOGOS_BY_ID[717],
    'sarmiento': ARG_CLUB_LOGOS_BY_ID[718],
    'sarmiento de junin': ARG_CLUB_LOGOS_BY_ID[718],
    'central cordoba': ARG_CLUB_LOGOS_BY_ID[719],
    'central cordoba sde': ARG_CLUB_LOGOS_BY_ID[719],
    'barracas central': ARG_CLUB_LOGOS_BY_ID[720],
    'platense': ARG_CLUB_LOGOS_BY_ID[722],
    'tigre': ARG_CLUB_LOGOS_BY_ID[723],
    'union': ARG_CLUB_LOGOS_BY_ID[724],
    'union de santa fe': ARG_CLUB_LOGOS_BY_ID[724],
    'argentinos juniors': ARG_CLUB_LOGOS_BY_ID[726],
    'deportivo riestra': ARG_CLUB_LOGOS_BY_ID[727],
    'riestra': ARG_CLUB_LOGOS_BY_ID[727],
    'gimnasia mendoza': ARG_CLUB_LOGOS_BY_ID[728],
    'gimnasia y esgrima mendoza': ARG_CLUB_LOGOS_BY_ID[728],
    'gimnasia lp': ARG_CLUB_LOGOS_BY_ID[729],
    'gimnasia la plata': ARG_CLUB_LOGOS_BY_ID[729],
    'banfield': ARG_CLUB_LOGOS_BY_ID[730],
    'independiente rivadavia': ARG_CLUB_LOGOS_BY_ID[731],
    'aldosivi': ARG_CLUB_LOGOS_BY_ID[732],
    'estudiantes rio cuarto': ARG_CLUB_LOGOS_BY_ID[733],

    // Primera Nacional
    'chaco for ever': ARG_CLUB_LOGOS_BY_ID[753],
    'nueva chicago': ARG_CLUB_LOGOS_BY_ID[754],
    'almagro': ARG_CLUB_LOGOS_BY_ID[755],
    'all boys': ARG_CLUB_LOGOS_BY_ID[756],
    'estudiantes ba': ARG_CLUB_LOGOS_BY_ID[757],
    'estudiantes de buenos aires': ARG_CLUB_LOGOS_BY_ID[757],
    'deportivo moron': ARG_CLUB_LOGOS_BY_ID[759],
    'moron': ARG_CLUB_LOGOS_BY_ID[759],
    'ferro carril oeste': ARG_CLUB_LOGOS_BY_ID[760],
    'ferro': ARG_CLUB_LOGOS_BY_ID[760],
    'agropecuario': ARG_CLUB_LOGOS_BY_ID[761],
    'almirante brown': ARG_CLUB_LOGOS_BY_ID[762],
    'chacarita juniors': ARG_CLUB_LOGOS_BY_ID[764],
    'chacarita': ARG_CLUB_LOGOS_BY_ID[764],
    'temperley': ARG_CLUB_LOGOS_BY_ID[765],
    'mitre': ARG_CLUB_LOGOS_BY_ID[766],
    'mitre sde': ARG_CLUB_LOGOS_BY_ID[766],
    'colon': ARG_CLUB_LOGOS_BY_ID[767],
    'colon de santa fe': ARG_CLUB_LOGOS_BY_ID[767],
    'quilmes': ARG_CLUB_LOGOS_BY_ID[770],
    'central norte': ARG_CLUB_LOGOS_BY_ID[771],
    'defensores de belgrano': ARG_CLUB_LOGOS_BY_ID[773],
    'deportivo madryn': ARG_CLUB_LOGOS_BY_ID[774],
    'los andes': ARG_CLUB_LOGOS_BY_ID[775],
    'racing de cordoba': ARG_CLUB_LOGOS_BY_ID[776],
    'san miguel': ARG_CLUB_LOGOS_BY_ID[777],
    'san telmo': ARG_CLUB_LOGOS_BY_ID[778],
    'atlanta': ARG_CLUB_LOGOS_BY_ID[779],
    'colegiales': ARG_CLUB_LOGOS_BY_ID[781],
    'deportivo maipu': ARG_CLUB_LOGOS_BY_ID[782],
    'gimnasia jujuy': ARG_CLUB_LOGOS_BY_ID[784],
    'gimnasia y tiro': ARG_CLUB_LOGOS_BY_ID[785],
    'guemes': ARG_CLUB_LOGOS_BY_ID[786],
    'patronato': ARG_CLUB_LOGOS_BY_ID[787],
    'san martin de tucuman': ARG_CLUB_LOGOS_BY_ID[788],
    'san martin tucuman': ARG_CLUB_LOGOS_BY_ID[788],
    'tristan suarez': ARG_CLUB_LOGOS_BY_ID[789],
};
