/**
 * Vector SVG badges and club logos from Community Data Packs
 * Source: https://github.com/Extremer12/community-data-packs (Extremer12/community-data-packs@main)
 * CDN: jsDelivr
 * 
 * Folders:
 * - Argentina/primera_division/
 * - Argentina/primera_nacional/
 * - Premier League/
 * - Championship/
 */

export const COMMUNITY_PACK_CDN = 'https://cdn.jsdelivr.net/gh/Extremer12/community-data-packs@main';
export const ARG_PACK_CDN = COMMUNITY_PACK_CDN; // Backwards-compatible alias

export const ARG_COMPETITION_LOGOS: Record<string, string> = {
    LIGA_ARGENTINA: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_argentina-primera-division.football-logos.cc.svg`,
    PRIMERA_NACIONAL: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_primera-nacional.football-logos.cc.svg`,
    PREMIER_LEAGUE: `${COMMUNITY_PACK_CDN}/Premier%20League/england_english-premier-league.football-logos.cc.svg`,
    CHAMPIONSHIP: `${COMMUNITY_PACK_CDN}/Championship/england_efl-championship.football-logos.cc.svg`,
    'liga-argentina': `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_argentina-primera-division.football-logos.cc.svg`,
    'primera-nacional': `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_primera-nacional.football-logos.cc.svg`,
    'premier-league': `${COMMUNITY_PACK_CDN}/Premier%20League/england_english-premier-league.football-logos.cc.svg`,
    'championship': `${COMMUNITY_PACK_CDN}/Championship/england_efl-championship.football-logos.cc.svg`,
};

export const ARG_CLUB_LOGOS_BY_ID: Record<number | string, string> = {
    // ==========================================
    // Primera División (IDs 701-733)
    // ==========================================
    701: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_boca-juniors.football-logos.cc.svg`,
    702: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_river-plate.football-logos.cc.svg`,
    703: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_racing-club.football-logos.cc.svg`,
    704: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_independiente.football-logos.cc.svg`,
    705: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_san-lorenzo-de-almagro.football-logos.cc.svg`,
    706: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_estudiantes-de-la-plata.football-logos.cc.svg`,
    707: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_velez-sarsfield.football-logos.cc.svg`,
    708: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_ca-huracan.football-logos.cc.svg`,
    709: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_rosario-central.football-logos.cc.svg`,
    710: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_newells-old-boys.football-logos.cc.svg`,
    711: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_talleres.football-logos.cc.svg`,
    712: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_atletico-tucuman.football-logos.cc.svg`,
    714: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_defensa-y-justicia.football-logos.cc.svg`,
    715: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_lanus.football-logos.cc.svg`,
    716: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_belgrano.football-logos.cc.svg`,
    717: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_instituto-cordoba.football-logos.cc.svg`,
    718: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_sarmiento.football-logos.cc.svg`,
    719: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_central-cordoba.football-logos.cc.svg`,
    720: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_barracas-central.football-logos.cc.svg`,
    722: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_club-atletico-platanense.football-logos.cc.svg`,
    723: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_tigre.football-logos.cc.svg`,
    724: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_union.football-logos.cc.svg`,
    726: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_argeninos-juniors.football-logos.cc.svg`,
    727: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_deportivo-riestra.football-logos.cc.svg`,
    728: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_gimnasia-y-esgrima.football-logos.cc.svg`,
    729: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_gimnasia-lp.football-logos.cc.svg`,
    730: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_banfield.football-logos.cc.svg`,
    731: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_independiente-rivadavia.football-logos.cc.svg`,
    732: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_aldosivi.football-logos.cc.svg`,
    733: `${COMMUNITY_PACK_CDN}/Argentina/primera_division/argentina_estudiantes-de-rio-cuarto.football-logos.cc.svg`,

    // ==========================================
    // Primera Nacional (IDs 750+)
    // ==========================================
    753: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_chaco-for-ever.football-logos.cc.svg`,
    754: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_nueva-chicago.football-logos.cc.svg`,
    755: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_almagro.football-logos.cc.svg`,
    756: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_all-boys.football-logos.cc.svg`,
    757: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_estudiantes-de-buenos-aires.football-logos.cc.svg`,
    759: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_deportivo-moron.football-logos.cc.svg`,
    760: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_ferro-carril-oeste.football-logos.cc.svg`,
    761: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_agropecuario-argentino.football-logos.cc.svg`,
    762: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_almirante-brown.football-logos.cc.svg`,
    764: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_chacarita-juniors.football-logos.cc.svg`,
    765: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_temperley.football-logos.cc.svg`,
    766: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_mitre-santiago-del-estero.football-logos.cc.svg`,
    767: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_colon-santa-fe.football-logos.cc.svg`,
    770: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_quilmes.football-logos.cc.svg`,
    771: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_central-norte.football-logos.cc.svg`,
    773: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_defensores-de-belgrano.football-logos.cc.svg`,
    774: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_deportivo-madryn.football-logos.cc.svg`,
    775: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_los-andes.football-logos.cc.svg`,
    776: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_racing.football-logos.cc.svg`,
    777: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_san-miguel.football-logos.cc.svg`,
    778: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_san-telmo.football-logos.cc.svg`,
    779: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_atletico-atlanta.football-logos.cc.svg`,
    781: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_colegiales.football-logos.cc.svg`,
    782: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_deportivo-maipu.football-logos.cc.svg`,
    784: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_gimnasia-de-jujuy.football-logos.cc.svg`,
    785: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_gimnasia-y-tiro.football-logos.cc.svg`,
    786: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_guemes.football-logos.cc.svg`,
    787: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_patronato.football-logos.cc.svg`,
    788: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_san-martin-tucuman.football-logos.cc.svg`,
    789: `${COMMUNITY_PACK_CDN}/Argentina/primera_nacional/argentina_tristan-suarez.football-logos.cc.svg`,

    // ==========================================
    // Premier League (IDs 1-20)
    // ==========================================
    1: `${COMMUNITY_PACK_CDN}/Premier%20League/england_arsenal.football-logos.cc.svg`,
    2: `${COMMUNITY_PACK_CDN}/Premier%20League/england_aston-villa.football-logos.cc.svg`,
    3: `${COMMUNITY_PACK_CDN}/Premier%20League/england_chelsea.football-logos.cc.svg`,
    4: `${COMMUNITY_PACK_CDN}/Premier%20League/england_liverpool.football-logos.cc.svg`,
    5: `${COMMUNITY_PACK_CDN}/Premier%20League/england_manchester-city.football-logos.cc.svg`,
    6: `${COMMUNITY_PACK_CDN}/Premier%20League/england_manchester-united.football-logos.cc.svg`,
    7: `${COMMUNITY_PACK_CDN}/Premier%20League/england_newcastle.football-logos.cc.svg`,
    8: `${COMMUNITY_PACK_CDN}/Premier%20League/england_tottenham.football-logos.cc.svg`,
    9: `${COMMUNITY_PACK_CDN}/Championship/england_west-ham.football-logos.cc.svg`,
    10: `${COMMUNITY_PACK_CDN}/Premier%20League/england_brighton.football-logos.cc.svg`,
    11: `${COMMUNITY_PACK_CDN}/Premier%20League/england_fulham.football-logos.cc.svg`,
    12: `${COMMUNITY_PACK_CDN}/Premier%20League/england_crystal-palace.football-logos.cc.svg`,
    13: `${COMMUNITY_PACK_CDN}/Premier%20League/england_brentford.football-logos.cc.svg`,
    14: `${COMMUNITY_PACK_CDN}/Premier%20League/england_everton.football-logos.cc.svg`,
    15: `${COMMUNITY_PACK_CDN}/Premier%20League/england_nottingham-forest.football-logos.cc.svg`,
    16: `${COMMUNITY_PACK_CDN}/Premier%20League/england_bournemouth.football-logos.cc.svg`,
    17: `${COMMUNITY_PACK_CDN}/Championship/england_wolves.football-logos.cc.svg`,
    18: `${COMMUNITY_PACK_CDN}/Premier%20League/england_ipswich.football-logos.cc.svg`,
    19: `${COMMUNITY_PACK_CDN}/Premier%20League/england_english-premier-league.football-logos.cc.svg`,
    20: `${COMMUNITY_PACK_CDN}/Championship/england_southampton.football-logos.cc.svg`,

    // ==========================================
    // Championship (IDs 101-124)
    // ==========================================
    101: `${COMMUNITY_PACK_CDN}/Premier%20League/england_leeds-united.football-logos.cc.svg`,
    102: `${COMMUNITY_PACK_CDN}/Championship/england_burnley.football-logos.cc.svg`,
    103: `${COMMUNITY_PACK_CDN}/Championship/england_luton.football-logos.cc.svg`,
    104: `${COMMUNITY_PACK_CDN}/Championship/england_sheffield-united.football-logos.cc.svg`,
    105: `${COMMUNITY_PACK_CDN}/Championship/england_west-bromwich-albion.football-logos.cc.svg`,
    106: `${COMMUNITY_PACK_CDN}/Championship/england_norwich-city.football-logos.cc.svg`,
    107: `${COMMUNITY_PACK_CDN}/Premier%20League/england_hull-city.football-logos.cc.svg`,
    108: `${COMMUNITY_PACK_CDN}/Championship/england_coventry.football-logos.cc.svg`,
    109: `${COMMUNITY_PACK_CDN}/Championship/england_middlesbrough.football-logos.cc.svg`,
    110: `${COMMUNITY_PACK_CDN}/Championship/england_preston-north-end.football-logos.cc.svg`,
    111: `${COMMUNITY_PACK_CDN}/Championship/england_cardiff-city.football-logos.cc.svg`,
    112: `${COMMUNITY_PACK_CDN}/Championship/england_bristol-city.football-logos.cc.svg`,
    113: `${COMMUNITY_PACK_CDN}/Premier%20League/england_sunderland.football-logos.cc.svg`,
    114: `${COMMUNITY_PACK_CDN}/Championship/england_swansea-city.football-logos.cc.svg`,
    115: `${COMMUNITY_PACK_CDN}/Championship/england_watford.football-logos.cc.svg`,
    116: `${COMMUNITY_PACK_CDN}/Championship/england_millwall.football-logos.cc.svg`,
    117: `${COMMUNITY_PACK_CDN}/Championship/england_queens-park-rangers.football-logos.cc.svg`,
    118: `${COMMUNITY_PACK_CDN}/Championship/england_stoke-city.football-logos.cc.svg`,
    119: `${COMMUNITY_PACK_CDN}/Championship/england_blackburn-rovers.football-logos.cc.svg`,
    120: `${COMMUNITY_PACK_CDN}/Championship/england_sheffield-wednesday.football-logos.cc.svg`,
    121: `${COMMUNITY_PACK_CDN}/Championship/england_plymouth.football-logos.cc.svg`,
    122: `${COMMUNITY_PACK_CDN}/Championship/england_portsmouth.football-logos.cc.svg`,
    123: `${COMMUNITY_PACK_CDN}/Championship/england_derby-county.football-logos.cc.svg`,
    124: `${COMMUNITY_PACK_CDN}/Championship/england_oxford.football-logos.cc.svg`,
};

export const ARG_CLUB_LOGOS_BY_NAME: Record<string, string> = {
    // Argentina - Primera División
    'boca juniors': ARG_CLUB_LOGOS_BY_ID[701],
    'river plate': ARG_CLUB_LOGOS_BY_ID[702],
    'racing club': ARG_CLUB_LOGOS_BY_ID[703],
    'independiente': ARG_CLUB_LOGOS_BY_ID[704],
    'san lorenzo': ARG_CLUB_LOGOS_BY_ID[705],
    'san lorenzo de almagro': ARG_CLUB_LOGOS_BY_ID[705],
    'estudiantes': ARG_CLUB_LOGOS_BY_ID[706],
    'estudiantes de la plata': ARG_CLUB_LOGOS_BY_ID[706],
    'estudiantes lp': ARG_CLUB_LOGOS_BY_ID[706],
    'velez sarsfield': ARG_CLUB_LOGOS_BY_ID[707],
    'velez': ARG_CLUB_LOGOS_BY_ID[707],
    'huracan': ARG_CLUB_LOGOS_BY_ID[708],
    'ca huracan': ARG_CLUB_LOGOS_BY_ID[708],
    'rosario central': ARG_CLUB_LOGOS_BY_ID[709],
    'newells old boys': ARG_CLUB_LOGOS_BY_ID[710],
    'newells': ARG_CLUB_LOGOS_BY_ID[710],
    'talleres': ARG_CLUB_LOGOS_BY_ID[711],
    'talleres cordoba': ARG_CLUB_LOGOS_BY_ID[711],
    'talleres de cordoba': ARG_CLUB_LOGOS_BY_ID[711],
    'atletico tucuman': ARG_CLUB_LOGOS_BY_ID[712],
    'defensa y justicia': ARG_CLUB_LOGOS_BY_ID[714],
    'lanus': ARG_CLUB_LOGOS_BY_ID[715],
    'belgrano': ARG_CLUB_LOGOS_BY_ID[716],
    'instituto': ARG_CLUB_LOGOS_BY_ID[717],
    'instituto cordoba': ARG_CLUB_LOGOS_BY_ID[717],
    'sarmiento': ARG_CLUB_LOGOS_BY_ID[718],
    'sarmiento de junin': ARG_CLUB_LOGOS_BY_ID[718],
    'central cordoba': ARG_CLUB_LOGOS_BY_ID[719],
    'central cordoba sde': ARG_CLUB_LOGOS_BY_ID[719],
    'barracas central': ARG_CLUB_LOGOS_BY_ID[720],
    'platense': ARG_CLUB_LOGOS_BY_ID[722],
    'tigre': ARG_CLUB_LOGOS_BY_ID[723],
    'union': ARG_CLUB_LOGOS_BY_ID[724],
    'union de santa fe': ARG_CLUB_LOGOS_BY_ID[724],
    'argentinos juniors': ARG_CLUB_LOGOS_BY_ID[726],
    'deportivo riestra': ARG_CLUB_LOGOS_BY_ID[727],
    'riestra': ARG_CLUB_LOGOS_BY_ID[727],
    'gimnasia mendoza': ARG_CLUB_LOGOS_BY_ID[728],
    'gimnasia y esgrima mendoza': ARG_CLUB_LOGOS_BY_ID[728],
    'gimnasia lp': ARG_CLUB_LOGOS_BY_ID[729],
    'gimnasia la plata': ARG_CLUB_LOGOS_BY_ID[729],
    'banfield': ARG_CLUB_LOGOS_BY_ID[730],
    'independiente rivadavia': ARG_CLUB_LOGOS_BY_ID[731],
    'aldosivi': ARG_CLUB_LOGOS_BY_ID[732],
    'estudiantes rio cuarto': ARG_CLUB_LOGOS_BY_ID[733],

    // Argentina - Primera Nacional
    'chaco for ever': ARG_CLUB_LOGOS_BY_ID[753],
    'nueva chicago': ARG_CLUB_LOGOS_BY_ID[754],
    'almagro': ARG_CLUB_LOGOS_BY_ID[755],
    'all boys': ARG_CLUB_LOGOS_BY_ID[756],
    'estudiantes ba': ARG_CLUB_LOGOS_BY_ID[757],
    'estudiantes de buenos aires': ARG_CLUB_LOGOS_BY_ID[757],
    'deportivo moron': ARG_CLUB_LOGOS_BY_ID[759],
    'moron': ARG_CLUB_LOGOS_BY_ID[759],
    'ferro carril oeste': ARG_CLUB_LOGOS_BY_ID[760],
    'ferro': ARG_CLUB_LOGOS_BY_ID[760],
    'agropecuario': ARG_CLUB_LOGOS_BY_ID[761],
    'almirante brown': ARG_CLUB_LOGOS_BY_ID[762],
    'chacarita juniors': ARG_CLUB_LOGOS_BY_ID[764],
    'chacarita': ARG_CLUB_LOGOS_BY_ID[764],
    'temperley': ARG_CLUB_LOGOS_BY_ID[765],
    'mitre': ARG_CLUB_LOGOS_BY_ID[766],
    'mitre sde': ARG_CLUB_LOGOS_BY_ID[766],
    'colon': ARG_CLUB_LOGOS_BY_ID[767],
    'colon de santa fe': ARG_CLUB_LOGOS_BY_ID[767],
    'quilmes': ARG_CLUB_LOGOS_BY_ID[770],
    'central norte': ARG_CLUB_LOGOS_BY_ID[771],
    'defensores de belgrano': ARG_CLUB_LOGOS_BY_ID[773],
    'deportivo madryn': ARG_CLUB_LOGOS_BY_ID[774],
    'los andes': ARG_CLUB_LOGOS_BY_ID[775],
    'racing de cordoba': ARG_CLUB_LOGOS_BY_ID[776],
    'san miguel': ARG_CLUB_LOGOS_BY_ID[777],
    'san telmo': ARG_CLUB_LOGOS_BY_ID[778],
    'atlanta': ARG_CLUB_LOGOS_BY_ID[779],
    'colegiales': ARG_CLUB_LOGOS_BY_ID[781],
    'deportivo maipu': ARG_CLUB_LOGOS_BY_ID[782],
    'gimnasia jujuy': ARG_CLUB_LOGOS_BY_ID[784],
    'gimnasia y tiro': ARG_CLUB_LOGOS_BY_ID[785],
    'guemes': ARG_CLUB_LOGOS_BY_ID[786],
    'patronato': ARG_CLUB_LOGOS_BY_ID[787],
    'san martin de tucuman': ARG_CLUB_LOGOS_BY_ID[788],
    'san martin tucuman': ARG_CLUB_LOGOS_BY_ID[788],
    'tristan suarez': ARG_CLUB_LOGOS_BY_ID[789],

    // England - Premier League
    'arsenal': ARG_CLUB_LOGOS_BY_ID[1],
    'aston villa': ARG_CLUB_LOGOS_BY_ID[2],
    'chelsea': ARG_CLUB_LOGOS_BY_ID[3],
    'liverpool': ARG_CLUB_LOGOS_BY_ID[4],
    'manchester city': ARG_CLUB_LOGOS_BY_ID[5],
    'man city': ARG_CLUB_LOGOS_BY_ID[5],
    'manchester utd': ARG_CLUB_LOGOS_BY_ID[6],
    'manchester united': ARG_CLUB_LOGOS_BY_ID[6],
    'man utd': ARG_CLUB_LOGOS_BY_ID[6],
    'newcastle utd': ARG_CLUB_LOGOS_BY_ID[7],
    'newcastle united': ARG_CLUB_LOGOS_BY_ID[7],
    'newcastle': ARG_CLUB_LOGOS_BY_ID[7],
    'tottenham': ARG_CLUB_LOGOS_BY_ID[8],
    'tottenham hotspur': ARG_CLUB_LOGOS_BY_ID[8],
    'spurs': ARG_CLUB_LOGOS_BY_ID[8],
    'west ham': ARG_CLUB_LOGOS_BY_ID[9],
    'west ham united': ARG_CLUB_LOGOS_BY_ID[9],
    'brighton': ARG_CLUB_LOGOS_BY_ID[10],
    'brighton and hove albion': ARG_CLUB_LOGOS_BY_ID[10],
    'brighton & hove albion': ARG_CLUB_LOGOS_BY_ID[10],
    'fulham': ARG_CLUB_LOGOS_BY_ID[11],
    'crystal palace': ARG_CLUB_LOGOS_BY_ID[12],
    'brentford': ARG_CLUB_LOGOS_BY_ID[13],
    'everton': ARG_CLUB_LOGOS_BY_ID[14],
    'nottm forest': ARG_CLUB_LOGOS_BY_ID[15],
    'nottingham forest': ARG_CLUB_LOGOS_BY_ID[15],
    'bournemouth': ARG_CLUB_LOGOS_BY_ID[16],
    'afc bournemouth': ARG_CLUB_LOGOS_BY_ID[16],
    'wolves': ARG_CLUB_LOGOS_BY_ID[17],
    'wolverhampton': ARG_CLUB_LOGOS_BY_ID[17],
    'wolverhampton wanderers': ARG_CLUB_LOGOS_BY_ID[17],
    'ipswich town': ARG_CLUB_LOGOS_BY_ID[18],
    'ipswich': ARG_CLUB_LOGOS_BY_ID[18],
    'leicester city': ARG_CLUB_LOGOS_BY_ID[19],
    'leicester': ARG_CLUB_LOGOS_BY_ID[19],
    'southampton': ARG_CLUB_LOGOS_BY_ID[20],

    // England - Championship
    'leeds united': ARG_CLUB_LOGOS_BY_ID[101],
    'leeds': ARG_CLUB_LOGOS_BY_ID[101],
    'burnley': ARG_CLUB_LOGOS_BY_ID[102],
    'luton town': ARG_CLUB_LOGOS_BY_ID[103],
    'luton': ARG_CLUB_LOGOS_BY_ID[103],
    'sheffield utd': ARG_CLUB_LOGOS_BY_ID[104],
    'sheffield united': ARG_CLUB_LOGOS_BY_ID[104],
    'west brom': ARG_CLUB_LOGOS_BY_ID[105],
    'west bromwich albion': ARG_CLUB_LOGOS_BY_ID[105],
    'norwich city': ARG_CLUB_LOGOS_BY_ID[106],
    'norwich': ARG_CLUB_LOGOS_BY_ID[106],
    'hull city': ARG_CLUB_LOGOS_BY_ID[107],
    'hull': ARG_CLUB_LOGOS_BY_ID[107],
    'coventry city': ARG_CLUB_LOGOS_BY_ID[108],
    'coventry': ARG_CLUB_LOGOS_BY_ID[108],
    'middlesbrough': ARG_CLUB_LOGOS_BY_ID[109],
    'preston': ARG_CLUB_LOGOS_BY_ID[110],
    'preston north end': ARG_CLUB_LOGOS_BY_ID[110],
    'cardiff city': ARG_CLUB_LOGOS_BY_ID[111],
    'cardiff': ARG_CLUB_LOGOS_BY_ID[111],
    'bristol city': ARG_CLUB_LOGOS_BY_ID[112],
    'sunderland': ARG_CLUB_LOGOS_BY_ID[113],
    'swansea city': ARG_CLUB_LOGOS_BY_ID[114],
    'swansea': ARG_CLUB_LOGOS_BY_ID[114],
    'watford': ARG_CLUB_LOGOS_BY_ID[115],
    'millwall': ARG_CLUB_LOGOS_BY_ID[116],
    'qpr': ARG_CLUB_LOGOS_BY_ID[117],
    'queens park rangers': ARG_CLUB_LOGOS_BY_ID[117],
    'stoke city': ARG_CLUB_LOGOS_BY_ID[118],
    'stoke': ARG_CLUB_LOGOS_BY_ID[118],
    'blackburn': ARG_CLUB_LOGOS_BY_ID[119],
    'blackburn rovers': ARG_CLUB_LOGOS_BY_ID[119],
    'sheffield wed': ARG_CLUB_LOGOS_BY_ID[120],
    'sheffield wednesday': ARG_CLUB_LOGOS_BY_ID[120],
    'plymouth': ARG_CLUB_LOGOS_BY_ID[121],
    'plymouth argyle': ARG_CLUB_LOGOS_BY_ID[121],
    'portsmouth': ARG_CLUB_LOGOS_BY_ID[122],
    'derby county': ARG_CLUB_LOGOS_BY_ID[123],
    'derby': ARG_CLUB_LOGOS_BY_ID[123],
    'oxford united': ARG_CLUB_LOGOS_BY_ID[124],
    'oxford': ARG_CLUB_LOGOS_BY_ID[124],
};
